In [1]:
import pandas as pd
import numpy as np
from collections import Counter
import geocoder

In [2]:
# read in dataframe
df = pd.read_excel("CURA Dunham 1950-53 .xlsx")

In [3]:
# lowercase columns
df.columns = [x.lower() for x in df.columns]
df.columns = [x.strip() for x in df.columns]
df.columns = [x.replace(" ", "_") for x in df.columns]

In [44]:
#df = pd.read_csv('g2.csv')

In [6]:
df['lat'] = None
df['lng'] = None
df['geocoded_location'] = None

In [7]:
# this is where we geocode
for i, v in df.iterrows():

    if pd.isnull(df['lat'][i]):
        print(str(v['city_1']) + "," + str(v['country_1']))
        try:
            g = geocoder.google(str(v['city_1']) + "," + str(v['country_1']))
            df['lat'][i] = g.lat
            df['lng'][i] = g.lng
            df['location'][i] = g.location
        except Exception as e:
            print(e)
            df['lat'][i] = None
            df['lng'][i] = None
            df['geocoded_location'][i] = None

Paris,France

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/usr/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Cairo,Egypt
Cairo,Egypt
Cairo,Egypt
Cairo,Egypt
Cairo,Egypt
Rome,Italy
Turin,Italy
Turin,Italy
Genoa,Italy
Genoa,Italy
nan,nan
Naples,Italy
Naples,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
nan,nan
Florence,Italy
Florence,Italy
Florence,Italy
Florence,Italy
Bologna,Italy
Bologna,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Venice,Italy
Venice,Italy
Venice,Italy
Milan,Italy
Piacenza,Italy
Brescia,Italy
Biella,Italy
Genoa,Italy
Milan,Italy
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
New York City,USA
Belem,Brazil
Belem,Brazil
Recife,Brazil
Recife,Brazil
Recife,Brazil
Recife,Brazil
Recife,Brazil
Recife,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Sao Paulo,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Rio de Janeiro,Brazil
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Montevideo,Uruguay
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
nan,nan
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Santiago,Chile
Buenos Aires,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Mar del Plata,Argentina
Buenos Aires,Argentina
Buenos Aires,Argentina
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Lima,Peru
Quito,Ecuador
Quito,Ecuador
Quito,Ecuador
Quito,Ecuador
Cali,Colombia
Cali,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Bogota,Colombia
Medellin,Colombia
Medellin,Colombia
Barranquilla,Colombia
Barranquilla,Colombia
Barranquilla,Colombia
Cartagena,Colombia
Barranquilla,Colombia
Barranquilla,Colombia
Barranquilla,Colombia
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Caracas,Venezuela
Kingston,Jamaica
Kingston,Jamaica
Petion-Ville,Haiti
Petion-Ville,Haiti
Petion-Ville,Haiti
Petion-Ville,Haiti
Petion-Ville,Haiti
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Kingston,Jamaica
Port au Prince,Haiti
Port au Prince,Haiti

Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port au Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Port-au-Prince,Haiti
Mexico City,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Guadalajara,Mexico
Mexico City,Mexico
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
nan,nan
NaT,NaT
NaT,NaT
NaT,NaT
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
New York,USA
New York,USA
New York,USA
nan,nan
New York,USA
Gander,Newfoundland
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
London,England
Cairnryan,Scotland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Belfast,Northern Ireland
Dublin,Ireland
Dublin,Ireland
Dublin,Ireland
Dublin,Ireland
Dublin,Ireland
Dublin,Ireland
Dublin,Ireland
London,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Bournemouth,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Nottingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Birmingham,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
Bristol,England
London,England
London,England
London,England
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Copenhagen,Denmark
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Vichy,France
Vichy,France
nan,France
nan,France
nan,France
Juan-les-Pins,France
nan,France
Marseille?,France
nan,France
Nice,France
nan,France
nan,France
Arachon,France
Arachon,France
nan,France
Biarritz,France
Biarritz,France
Biarritz,France
Biarritz,France

Biarritz,France
NaT,NaT
Dax,France
NaT,NaT
NaT,NaT
NaT,NaT
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
nan,nan
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Barcelona,Spain
Ventimiglia,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Milan,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Palermo,Italy
Palermo,Italy
Catania,Italy
Catania,Italy
Naples,Italy
Naples,Italy
Naples,Italy
Turin,Italy
Turin,Italy
Genoa,Italy
Genoa,Italy
Santa Margherita, Genoa,Italy
Santa Margherita, Genoa,Italy
Santa Margherita, Genoa,Italy
Santa Margherita, Genoa,Italy
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Marseille,France
Bern,Switzerland
Bern,Switzerland
Bern,Switzerland
Zurich,Switzerland
Zurich,Switzerland
Zurich,Switzerland
Zurich,Switzerland
nan,nan
Altreu,Switzerland
Lausanne,Switzerland
Basel,Switzerland
Basel,Switzerland
Rome,Italy
Rome,Italy
Sicily,Italy
Palermo,Italy
Palermo,Italy
Palermo,Italy
Catania,Italy
nan,nan
Bari,Italy
Bari,Italy
Naples,Italy
Naples,Italy
Naples,Italy
Naples,Italy
Livorno,Italy
Florence,Italy
Florence,Italy
Trieste,Italy
Trieste,Italy
Trieste,Italy
Padova,Italy
Brescia,Italy
Varese,Italy
Varese,Italy
Bergamo,Italy
Bergamo,Italy
Verona,Italy
Verona,Italy
Bologna,Italy
Bologna,Italy
Bologna,Italy
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
NaT,NaT
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Bordeaux,France
Bordeaux,France
nan,nan
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
Paris,France
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Oran,Algeria
Oran,Algeria
NaT,NaT
NaT,NaT
Casablanca,Morocco
Casablanca,Morocco
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Paris,France
Paris,France
New York City,USA
New York City,USA
Chicago,Illinois
NaT,NaT
NaT,NaT
Joliet,Illinois
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Hollywood,USA
Las Vegas,USA
Las Vegas,USA
Las Vegas,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Hollywood,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Reno,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
Vancouver,Canada
NaT,NaT
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Crystal Bay, NV,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
Hollywood,USA
nan,nan
nan,nan
Havana,Cuba
Havana,Cuba
Havana,Cuba
nan,nan
nan,nan
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
Los Angeles,USA
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
San Francisco,USA
San Francisco,USA
San Francisco,USA
San Francisco ,USA
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
Beverly Hills,USA
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
NaT,NaT
New York,USA
Paris,France
NaT,NaT
NaT,NaT
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy
Rome,Italy

In [98]:
df

,Unnamed: 0,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same,location
0,0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
1,1,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,None
2,2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.856614,2.352222,True,None
3,3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.856614,2.352222,True,None
4,4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,48.856614,2.352222,True,"Paris,France"
5,5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,48.856614,2.352222,True,None
6,6,1950-01-07,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,"Paris,France"
7,7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
8,8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
9,9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
10,10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
11,11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
12,12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
13,13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
14,14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
15,15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
16,16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
17,17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
18,18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
19,19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
20,20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
21,21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
22,22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
23,23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
24,24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
25,25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
26,26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7",48.856614,2.352222,True,None
27,27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
28,28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,None
29,29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,48.856614,2.352222,True,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1432,1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1433,1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1434,1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1435,1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1436,1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1437,1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1438,1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1439,1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,41.902784,12.496365,True,None
1440,1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1441,1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1442,1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1443,1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,None
1444,1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1445,1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1446,1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1447,1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,None
1448,1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1449,1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1450,1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1451,1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1452,1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1453,1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1454,1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1455,1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1456,1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1457,1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1458,1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1459,1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None
1460,1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,None

In [61]:
df['lat'][0].all()

True

In [40]:
df = df['lat'].fillna(0)

In [70]:
dir(df['lat'][383])

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_interface__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getformat__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setformat__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argsort',
 'as_integer_ratio',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'fromhex',
 'getfield',
 'hex',
 'imag',
 'is_integer',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

In [101]:
df[df['lat'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, date, city_1, country_1, city_2, country_2, working, source, lat, lng, same, location]
Index: []

In [8]:
df.to_csv('g4.csv')

In [9]:
df

,date,city_1,country_1,city_2,country_2,working,source,location,lat,lng,geocoded_location
0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
1,1950-01-02,Paris,France,NaN,NaN,y,NaN,"Paris,France",48.8566,2.35222,None
2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,"Paris,France",48.8566,2.35222,None
3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,"Paris,France",48.8566,2.35222,None
4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,"Paris,France",48.8566,2.35222,None
5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,"Paris,France",48.8566,2.35222,None
6,1950-01-07,Paris,France,NaN,NaN,y,NaN,"Paris,France",48.8566,2.35222,None
7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",None,None,None
11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7","Paris,France",48.8566,2.35222,None
27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",None,None,None
28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris,France",48.8566,2.35222,None
29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,"Paris,France",48.8566,2.35222,None
...,...,...,...,...,...,...,...,...,...,...,...
1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,"Rome,Italy",41.9028,12.4964,None
1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,"Rome,Italy",41.9028,12.4964,None
1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,"Rome,Italy",None,None,None
1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",None,None,None
1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None
1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN,"Rome,Italy",41.9028,12.4964,None