In [16]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dunham_join.csv')

In [3]:
df

,fid,Date,City 1,Country 1,City 2,Country 2,Working,Source,"City, Country","City, Country:1",lat:1,lng
0,1,1 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
1,2,2 Jan 1950,Paris,France,NaN,NaN,y,NaN,"Paris, France","Paris, France",48.859116,2.331839
2,3,3 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,"Paris, France","Paris, France",48.859116,2.331839
3,4,4 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,"Paris, France","Paris, France",48.859116,2.331839
4,5,5 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,"Paris, France","Paris, France",48.859116,2.331839
5,6,6 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,"Paris, France","Paris, France",48.859116,2.331839
6,7,7 Jan 1950,Paris,France,NaN,NaN,y,NaN,"Paris, France","Paris, France",48.859116,2.331839
7,8,8 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
8,9,9 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
9,10,10 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
10,11,11 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
11,12,12 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
12,13,13 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
13,14,14 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
14,15,15 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
15,16,16 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
16,17,17 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
17,18,18 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
18,19,19 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
19,20,20 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
20,21,21 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
21,22,22 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
22,23,23 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
23,24,24 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
24,25,25 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
25,26,26 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
26,27,27 Jan 1950,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7","Paris, France","Paris, France",48.859116,2.331839
27,28,28 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
28,29,29 Jan 1950,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,"Paris, France","Paris, France",48.859116,2.331839
29,30,30 Jan 1950,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,"Paris, France","Paris, France",48.859116,2.331839
...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1469,2 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1469,1470,3 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1470,1471,4 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1471,1472,5 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1472,1473,6 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1473,1474,7 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1474,1475,8 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1475,1476,9 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1476,1477,10 Dec 1953,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,"Rome, Italy","Rome, Italy",41.878243,12.528090
1477,1478,11 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1478,1479,12 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1479,1480,13 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1480,1481,14 Dec 1953,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,"Rome, Italy","Rome, Italy",41.878243,12.528090
1481,1482,15 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1482,1483,16 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1483,1484,17 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1484,1485,18 Dec 1953,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,"Rome, Italy","Rome, Italy",41.878243,12.528090
1485,1486,19 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1486,1487,20 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1487,1488,21 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1488,1489,22 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1489,1490,23 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1490,1491,24 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1491,1492,25 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1492,1493,26 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1493,1494,27 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1494,1495,28 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1495,1496,29 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1496,1497,30 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090
1497,1498,31 Dec 1953,Rome,Italy,NaN,NaN,y,NaN,"Rome, Italy","Rome, Italy",41.878243,12.528090

In [ ]:
# cast date/time

In [54]:
"""
Loop through data and count two things:

Length of stay = number of consecutive days in same city, call it a single 'trip' (may indicate success in an area)

# of returns to an city = number of trips to a city ( may indicate prefrence )
"""

def compare_previous(df, column):
    """
    compare previous row for change in column value
    """
    return df[column].eq(df[column].shift())

def count_duration(df, column):
    """
    count number of rows column value stays the same
    """
    return None
    

df['same'] = comp_prev(df, 'City, Country')
#change first entry value to true
df['same'][0] = True



    
# is x in this row the same x in previous row?

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

1 Paris, France True
2 Paris, France True
3 Paris, France True
4 Paris, France True
5 Paris, France True
6 Paris, France True
7 Paris, France True
8 Paris, France True
9 Paris, France True
10 Paris, France True
11 Paris, France True
12 Paris, France True
13 Paris, France True
14 Paris, France True
15 Paris, France True
16 Paris, France True
17 Paris, France True
18 Paris, France True
19 Paris, France True
20 Paris, France True
21 Paris, France True
22 Paris, France True
23 Paris, France True
24 Paris, France True
25 Paris, France True
26 Paris, France True
27 Paris, France True
28 Paris, France True
29 Paris, France True
30 Paris, France True
31 Cairo, Egypt False
32 Cairo, Egypt True
33 Cairo, Egypt True
34 Cairo, Egypt True
35 Cairo, Egypt True
36 Rome, Italy False
37 Turin, Italy False
38 Turin, Italy True
39 Genoa, Italy False
40 Genoa, Italy True
41 Genoa, Italy True
42 Genoa, Italy True
43 ,  False
44 Naples, Italy False
45 Naples, Italy True
46 Rome, Italy False
47 Rome, Italy True
48 Rome, Italy True
49 Rome, Italy True
50 Rome, Italy True
51 Rome, Italy True
52 Rome, Italy True
53 Rome, Italy True
54 Rome, Italy True
55 ,  False
56 Florence, Italy False
57 Florence, Italy True
58 Florence, Italy True
59 Florence, Italy True
60 Bologna, Italy False
61 Bologna, Italy True
62 Milan, Italy False
63 Milan, Italy True
64 Milan, Italy True
65 Milan, Italy True
66 Milan, Italy True
67 Milan, Italy True
68 Milan, Italy True
69 Milan, Italy True
70 Milan, Italy True
71 Milan, Italy True
72 Milan, Italy True
73 Milan, Italy True
74 Milan, Italy True
75 Milan, Italy True
76 Milan, Italy True
77 Milan, Italy True
78 Milan, Italy True
79 Milan, Italy True
80 Milan, Italy True
81 Milan, Italy True
82 Venice, Italy False
83 Venice, Italy True
84 Venice, Italy True
85 Milan, Italy False
86 Piacenza, Italy False
87 Brescia, Italy False
88 Biella, Italy False
89 Genoa, Italy False
90 Genoa, Italy True
91 Milan, Italy False
92 Paris, France False
93 Paris, France True
94 Paris, France True
95 Paris, France True
96 Paris, France True
97 Paris, France True
98 Paris, France True
99 Paris, France True
100 Paris, France True
101 Paris, France True
102 Paris, France True
103 Paris, France True
104 New York City, USA False
105 New York City, USA True
106 New York City, USA True
107 New York City, USA True
108 New York City, USA True
109 New York City, USA True
110 New York City, USA True
111 New York City, USA True
112 New York City, USA True
113 New York City, USA True
114 New York City, USA True
115 New York City, USA True
116 New York City, USA True
117 New York City, USA True
118 New York City, USA True
119 New York City, USA True
120 New York City, USA True
121 New York City, USA True
122 New York City, USA True
123 New York City, USA True
124 New York City, USA True
125 New York City, USA True
126 New York City, USA True
127 New York City, USA True
128 New York City, USA True
129 New York City, USA True
130 New York City, USA True
131 New York City, USA True
132 New York City, USA True
133 New York City, USA True
134 New York City, USA True
135 New York City, USA True
136 New York City, USA True
137 New York City, USA True
138 New York City, USA True
139 New York City, USA True
140 New York City, USA True
141 New York City, USA True
142 New York City, USA True
143 New York City, USA True
144 New York City, USA True
145 New York City, USA True
146 New York City, USA True
147 New York City, USA True
148 New York City, USA True
149 New York City, USA True
150 New York City, USA True
151 New York City, USA True
152 New York City, USA True
153 New York City, USA True
154 New York City, USA True
155 New York City, USA True
156 New York City, USA True
157 New York City, USA True
158 New York City, USA True
159 New York City, USA True
160 Belem, Brazil False
161 Belem, Brazil True
162 Recife, Brazil False
163 Recife, Brazil True
164 Recife, Brazil True
165 Recife, Brazil True
166 Recife, Brazil True
167 Recife, Brazil True
168 Rio de Janeiro, Brazil False
169 Rio de Janeiro, Brazil True
170 Rio de Janeiro, Brazil True
171 Rio de Janeiro, Brazil True
172 Rio de Janeiro, Brazil True
173 Rio de Janeiro, Brazil True
174 Rio de Janeiro, Brazil True
175 Rio de Janeiro, Brazil True
176 Rio de Janeiro, Brazil True
177 Rio de Janeiro, Brazil True
178 Rio de Janeiro, Brazil True
179 Rio de Janeiro, Brazil True
180 Rio de Janeiro, Brazil True
181 Rio de Janeiro, Brazil True
182 Rio de Janeiro, Brazil True
183 Rio de Janeiro, Brazil True
184 Rio de Janeiro, Brazil True
185 Rio de Janeiro, Brazil True
186 Rio de Janeiro, Brazil True
187 Rio de Janeiro, Brazil True
188 Rio de Janeiro, Brazil True
189 Rio de Janeiro, Brazil True
190 Rio de Janeiro, Brazil True
191 Rio de Janeiro, Brazil True
192 Rio de Janeiro, Brazil True
193 Rio de Janeiro, Brazil True
194 Rio de Janeiro, Brazil True
195 Sao Paulo, Brazil False
196 Sao Paulo, Brazil True
197 Sao Paulo, Brazil True
198 Sao Paulo, Brazil True
199 Sao Paulo, Brazil True
200 Sao Paulo, Brazil True
201 Sao Paulo, Brazil True
202 Sao Paulo, Brazil True
203 Sao Paulo, Brazil True
204 Sao Paulo, Brazil True
205 Sao Paulo, Brazil True
206 Sao Paulo, Brazil True
207 Sao Paulo, Brazil True
208 Sao Paulo, Brazil True
209 Sao Paulo, Brazil True
210 Sao Paulo, Brazil True
211 Sao Paulo, Brazil True
212 Sao Paulo, Brazil True
213 Sao Paulo, Brazil True
214 Rio de Janeiro, Brazil False
215 Rio de Janeiro, Brazil True
216 Rio de Janeiro, Brazil True
217 Rio de Janeiro, Brazil True
218 Rio de Janeiro, Brazil True
219 Rio de Janeiro, Brazil True
220 Rio de Janeiro, Brazil True
221 Rio de Janeiro, Brazil True
222 Rio de Janeiro, Brazil True
223 Rio de Janeiro, Brazil True
224 Rio de Janeiro, Brazil True
225 Rio de Janeiro, Brazil True
226 Rio de Janeiro, Brazil True
227 Rio de Janeiro, Brazil True
228 Rio de Janeiro, Brazil True
229 Rio de Janeiro, Brazil True
230 Montevideo, Uruguay False
231 Montevideo, Uruguay True
232 Montevideo, Uruguay True
233 Montevideo, Uruguay True
234 Montevideo, Uruguay True
235 Montevideo, Uruguay True
236 Montevideo, Uruguay True
237 Montevideo, Uruguay True
238 Montevideo, Uruguay True
239 Montevideo, Uruguay True
240 Montevideo, Uruguay True
241 Montevideo, Uruguay True
242 Montevideo, Uruguay True
243 Montevideo, Uruguay True
244 Montevideo, Uruguay True
245 Montevideo, Uruguay True
246 Buenos Aires, Argentina False
247 Buenos Aires, Argentina True
248 Buenos Aires, Argentina True
249 Buenos Aires, Argentina True
250 Buenos Aires, Argentina True
251 Buenos Aires, Argentina True
252 Buenos Aires, Argentina True
253 Buenos Aires, Argentina True
254 Buenos Aires, Argentina True
255 Buenos Aires, Argentina True
256 Buenos Aires, Argentina True
257 Buenos Aires, Argentina True
258 Buenos Aires, Argentina True
259 Buenos Aires, Argentina True
260 Buenos Aires, Argentina True
261 Buenos Aires, Argentina True
262 Buenos Aires, Argentina True
263 Buenos Aires, Argentina True
264 Buenos Aires, Argentina True
265 Buenos Aires, Argentina True
266 Buenos Aires, Argentina True
267 Buenos Aires, Argentina True
268 Buenos Aires, Argentina True
269 Buenos Aires, Argentina True
270 Buenos Aires, Argentina True
271 Buenos Aires, Argentina True
272 Buenos Aires, Argentina True
273 Buenos Aires, Argentina True
274 Buenos Aires, Argentina True
275 Buenos Aires, Argentina True
276 Buenos Aires, Argentina True
277 Buenos Aires, Argentina True
278 Buenos Aires, Argentina True
279 Buenos Aires, Argentina True
280 Buenos Aires, Argentina True
281 Buenos Aires, Argentina True
282 Buenos Aires, Argentina True
283 Buenos Aires, Argentina True
284 Buenos Aires, Argentina True
285 Buenos Aires, Argentina True
286 Buenos Aires, Argentina True
287 Buenos Aires, Argentina True
288 Buenos Aires, Argentina True
289 Buenos Aires, Argentina True
290 Buenos Aires, Argentina True
291 Buenos Aires, Argentina True
292 Buenos Aires, Argentina True
293 Buenos Aires, Argentina True
294 Buenos Aires, Argentina True
295 Buenos Aires, Argentina True
296 Buenos Aires, Argentina True
297 Buenos Aires, Argentina True
298 Buenos Aires, Argentina True
299 Buenos Aires, Argentina True
300 Buenos Aires, Argentina True
301 Buenos Aires, Argentina True
302 Buenos Aires, Argentina True
303 Buenos Aires, Argentina True
304 Buenos Aires, Argentina True
305 Buenos Aires, Argentina True
306 Buenos Aires, Argentina True
307 Buenos Aires, Argentina True
308 Buenos Aires, Argentina True
309 Buenos Aires, Argentina True
310 Buenos Aires, Argentina True
311 Buenos Aires, Argentina True
312 Buenos Aires, Argentina True
313 Buenos Aires, Argentina True
314 Buenos Aires, Argentina True
315 Buenos Aires, Argentina True
316 Buenos Aires, Argentina True
317 Buenos Aires, Argentina True
318 Buenos Aires, Argentina True
319 Buenos Aires, Argentina True
320 Buenos Aires, Argentina True
321 ,  False
322 ,  True
323 ,  True
324 ,  True
325 ,  True
326 ,  True
327 ,  True
328 ,  True
329 ,  True
330 ,  True
331 Santiago, Chile False
332 Santiago, Chile True
333 Santiago, Chile True
334 Santiago, Chile True
335 Santiago, Chile True
336 Santiago, Chile True
337 Santiago, Chile True
338 Santiago, Chile True
339 Santiago, Chile True
340 Santiago, Chile True
341 Santiago, Chile True
342 Santiago, Chile True
343 Santiago, Chile True
344 Santiago, Chile True
345 Santiago, Chile True
346 Santiago, Chile True
347 Santiago, Chile True
348 Santiago, Chile True
349 Buenos Aires, Argentina False
350 Mar del Plata, Argentina False
351 Mar del Plata, Argentina True
352 Mar del Plata, Argentina True
353 Mar del Plata, Argentina True
354 Mar del Plata, Argentina True
355 Mar del Plata, Argentina True
356 Mar del Plata, Argentina True
357 Mar del Plata, Argentina True
358 Mar del Plata, Argentina True
359 Mar del Plata, Argentina True
360 Mar del Plata, Argentina True
361 Mar del Plata, Argentina True
362 Mar del Plata, Argentina True
363 Mar del Plata, Argentina True
364 Mar del Plata, Argentina True
365 Mar del Plata, Argentina True
366 Mar del Plata, Argentina True
367 Mar del Plata, Argentina True
368 Mar del Plata, Argentina True
369 Mar del Plata, Argentina True
370 Mar del Plata, Argentina True
371 Mar del Plata, Argentina True
372 Buenos Aires, Argentina False
373 Buenos Aires, Argentina True
374 Lima, Peru False
375 Lima, Peru True
376 Lima, Peru True
377 Lima, Peru True
378 Lima, Peru True
379 Lima, Peru True
380 Lima, Peru True
381 Lima, Peru True
382 Lima, Peru True
383 Lima, Peru True
384 Lima, Peru True
385 Lima, Peru True
386 Lima, Peru True
387 Lima, Peru True
388 Lima, Peru True
389 Lima, Peru True
390 Lima, Peru True
391 Lima, Peru True
392 Lima, Peru True
393 Lima, Peru True
394 Lima, Peru True
395 Lima, Peru True
396 Lima, Peru True
397 Lima, Peru True
398 Quito, Ecuador False
399 Quito, Ecuador True
400 Quito, Ecuador True
401 Quito, Ecuador True
402 Cali, Colombia False
403 Cali, Colombia True
404 Bogota, Colombia False
405 Bogota, Colombia True
406 Bogota, Colombia True
407 Bogota, Colombia True
408 Bogota, Colombia True
409 Bogota, Colombia True
410 Bogota, Colombia True
411 Bogota, Colombia True
412 Bogota, Colombia True
413 Bogota, Colombia True
414 Bogota, Colombia True
415 Bogota, Colombia True
416 Bogota, Colombia True
417 Bogota, Colombia True
418 Bogota, Colombia True
419 Medellin, Colombia False
420 Medellin, Colombia True
421 Barranquilla, Colombia False
422 Barranquilla, Colombia True
423 Barranquilla, Colombia True
424 Cartagena, Colombia False
425 Barranquilla, Colombia False
426 Barranquilla, Colombia True
427 Barranquilla, Colombia True
428 Caracas, Venezuela False
429 Caracas, Venezuela True
430 Caracas, Venezuela True
431 Caracas, Venezuela True
432 Caracas, Venezuela True
433 Caracas, Venezuela True
434 Caracas, Venezuela True
435 Caracas, Venezuela True
436 Caracas, Venezuela True
437 Caracas, Venezuela True
438 Caracas, Venezuela True
439 Caracas, Venezuela True
440 Kingston, Jamaica False
441 Kingston, Jamaica True
442 Petion-Ville, Haiti False
443 Petion-Ville, Haiti True
444 Petion-Ville, Haiti True
445 Petion-Ville, Haiti True
446 Petion-Ville, Haiti True
447 Kingston, Jamaica False
448 Kingston, Jamaica True
449 Kingston, Jamaica True
450 Kingston, Jamaica True
451 Kingston, Jamaica True
452 Kingston, Jamaica True
453 Kingston, Jamaica True
454 Kingston, Jamaica True
455 Kingston, Jamaica True
456 Kingston, Jamaica True
457 Kingston, Jamaica True
458 Kingston, Jamaica True
459 Kingston, Jamaica True
460 Kingston, Jamaica True
461 Kingston, Jamaica True
462 Kingston, Jamaica True
463 Kingston, Jamaica True
464 Kingston, Jamaica True
465 Kingston, Jamaica True
466 Kingston, Jamaica True
467 Kingston, Jamaica True
468 Kingston, Jamaica True
469 Kingston, Jamaica True
470 Kingston, Jamaica True
471 Kingston, Jamaica True
472 Kingston, Jamaica True
473 Kingston, Jamaica True
474 Port au Prince, Haiti False
475 Port au Prince, Haiti True
476 Port au Prince, Haiti True
477 Port au Prince, Haiti True
478 Port au Prince, Haiti True
479 Port au Prince, Haiti True
480 Port au Prince, Haiti True
481 Port au Prince, Haiti True
482 Port au Prince, Haiti True
483 Port au Prince, Haiti True
484 Port au Prince, Haiti True
485 Port au Prince, Haiti True
486 Port au Prince, Haiti True
487 Port au Prince, Haiti True
488 Port au Prince, Haiti True
489 Port au Prince, Haiti True
490 Port au Prince, Haiti True
491 Port au Prince, Haiti True
492 Port au Prince, Haiti True
493 Port au Prince, Haiti True
494 Port au Prince, Haiti True
495 Port au Prince, Haiti True
496 Port au Prince, Haiti True
497 Port au Prince, Haiti True
498 Port au Prince, Haiti True
499 Port au Prince, Haiti True
500 Port au Prince, Haiti True
501 Port au Prince, Haiti True
502 Port au Prince, Haiti True
503 Port au Prince, Haiti True
504 Port au Prince, Haiti True
505 Port au Prince, Haiti True
506 Port au Prince, Haiti True
507 Port au Prince, Haiti True
508 Port au Prince, Haiti True
509 Port au Prince, Haiti True
510 Port au Prince, Haiti True
511 Port au Prince, Haiti True
512 Port au Prince, Haiti True
513 Port au Prince, Haiti True
514 Port au Prince, Haiti True
515 Port au Prince, Haiti True
516 Port au Prince, Haiti True
517 Port au Prince, Haiti True
518 Port au Prince, Haiti True
519 Port au Prince, Haiti True
520 Port au Prince, Haiti True
521 Port au Prince, Haiti True
522 Port au Prince, Haiti True
523 Port au Prince, Haiti True
524 Port au Prince, Haiti True
525 Port au Prince, Haiti True
526 Port au Prince, Haiti True
527 Port au Prince, Haiti True
528 Port au Prince, Haiti True
529 Port au Prince, Haiti True
530 Port au Prince, Haiti True
531 Port au Prince, Haiti True
532 Port au Prince, Haiti True
533 Port au Prince, Haiti True
534 Port au Prince, Haiti True
535 Port au Prince, Haiti True
536 Port au Prince, Haiti True
537 Port au Prince, Haiti True
538 Port au Prince, Haiti True
539 Port au Prince, Haiti True
540 Port au Prince, Haiti True
541 Port au Prince, Haiti True
542 Port au Prince, Haiti True
543 Port au Prince, Haiti True
544 Port au Prince, Haiti True
545 Port au Prince, Haiti True
546 Port au Prince, Haiti True
547 Port au Prince, Haiti True
548 Port au Prince, Haiti True
549 Port au Prince, Haiti True
550 Port au Prince, Haiti True
551 Port au Prince, Haiti True
552 Port au Prince, Haiti True
553 Port au Prince, Haiti True
554 Port au Prince, Haiti True
555 Port au Prince, Haiti True
556 Port-au-Prince, Haiti False
557 Port-au-Prince, Haiti True
558 Port-au-Prince, Haiti True
559 Port-au-Prince, Haiti True
560 Port-au-Prince, Haiti True
561 Port-au-Prince, Haiti True
562 Port-au-Prince, Haiti True
563 Port-au-Prince, Haiti True
564 Port-au-Prince, Haiti True
565 Port-au-Prince, Haiti True
566 Port-au-Prince, Haiti True
567 Port-au-Prince, Haiti True
568 Port-au-Prince, Haiti True
569 Port-au-Prince, Haiti True
570 Port-au-Prince, Haiti True
571 Port-au-Prince, Haiti True
572 Port-au-Prince, Haiti True
573 Port-au-Prince, Haiti True
574 Port-au-Prince, Haiti True
575 Port-au-Prince, Haiti True
576 Port-au-Prince, Haiti True
577 Port-au-Prince, Haiti True
578 Port-au-Prince, Haiti True
579 Port-au-Prince, Haiti True
580 Port-au-Prince, Haiti True
581 Port-au-Prince, Haiti True
582 Port-au-Prince, Haiti True
583 Port-au-Prince, Haiti True
584 Port-au-Prince, Haiti True
585 Port-au-Prince, Haiti True
586 Port-au-Prince, Haiti True
587 Port-au-Prince, Haiti True
588 Port-au-Prince, Haiti True
589 Port-au-Prince, Haiti True
590 Port-au-Prince, Haiti True
591 Port-au-Prince, Haiti True
592 Port-au-Prince, Haiti True
593 Port-au-Prince, Haiti True
594 Port-au-Prince, Haiti True
595 Port-au-Prince, Haiti True
596 Port-au-Prince, Haiti True
597 Port-au-Prince, Haiti True
598 Port-au-Prince, Haiti True
599 Port-au-Prince, Haiti True
600 Port-au-Prince, Haiti True
601 Port-au-Prince, Haiti True
602 Mexico City, Mexico False
603 Guadalajara, Mexico False
604 Guadalajara, Mexico True
605 Guadalajara, Mexico True
606 Guadalajara, Mexico True
607 Guadalajara, Mexico True
608 Guadalajara, Mexico True
609 Guadalajara, Mexico True
610 Guadalajara, Mexico True
611 Guadalajara, Mexico True
612 Guadalajara, Mexico True
613 Guadalajara, Mexico True
614 Mexico City, Mexico False
615 Las Vegas, USA False
616 Las Vegas, USA True
617 Las Vegas, USA True
618 Las Vegas, USA True
619 Las Vegas, USA True
620 Las Vegas, USA True
621 Las Vegas, USA True
622 Las Vegas, USA True
623 Las Vegas, USA True
624 Las Vegas, USA True
625 Las Vegas, USA True
626 Las Vegas, USA True
627 Las Vegas, USA True
628 Las Vegas, USA True
629 Las Vegas, USA True
630 Las Vegas, USA True
631 Las Vegas, USA True
632 Las Vegas, USA True
633 Reno, USA False
634 Reno, USA True
635 Reno, USA True
636 Reno, USA True
637 Reno, USA True
638 Reno, USA True
639 Reno, USA True
640 Reno, USA True
641 Reno, USA True
642 ,  False
643 ,  True
644 ,  True
645 ,  True
646 ,  True
647 ,  True
648 ,  True
649 ,  True
650 Hollywood, USA False
651 Hollywood, USA True
652 Hollywood, USA True
653 Hollywood, USA True
654 Hollywood, USA True
655 Hollywood, USA True
656 Hollywood, USA True
657 Hollywood, USA True
658 Hollywood, USA True
659 Hollywood, USA True
660 Hollywood, USA True
661 ,  False
662 ,  True
663 ,  True
664 ,  True
665 ,  True
666 New York, USA False
667 New York, USA True
668 New York, USA True
669 ,  False
670 New York, USA False
671 Gander, Newfoundland False
672 Paris, France False
673 Paris, France True
674 Paris, France True
675 Paris, France True
676 Paris, France True
677 Paris, France True
678 Paris, France True
679 Paris, France True
680 Paris, France True
681 Paris, France True
682 Paris, France True
683 Paris, France True
684 Paris, France True
685 Paris, France True
686 Paris, France True
687 Paris, France True
688 Paris, France True
689 Paris, France True
690 Paris, France True
691 Paris, France True
692 Paris, France True
693 Paris, France True
694 Paris, France True
695 Paris, France True
696 Paris, France True
697 Paris, France True
698 Paris, France True
699 Paris, France True
700 Paris, France True
701 Paris, France True
702 Paris, France True
703 Paris, France True
704 Paris, France True
705 Paris, France True
706 Paris, France True
707 Paris, France True
708 Paris, France True
709 Paris, France True
710 Paris, France True
711 Paris, France True
712 Paris, France True

713 Paris, France True
714 Paris, France True
715 Paris, France True
716 Paris, France True
717 Paris, France True
718 Paris, France True
719 Paris, France True
720 Paris, France True
721 Paris, France True
722 Paris, France True
723 Paris, France True
724 Paris, France True
725 Paris, France True
726 Paris, France True
727 Paris, France True
728 Paris, France True
729 Paris, France True
730 Paris, France True
731 Paris, France True
732 Paris, France True
733 Paris, France True
734 Paris, France True
735 Paris, France True
736 Paris, France True
737 Paris, France True
738 Paris, France True
739 Paris, France True
740 Paris, France True
741 Paris, France True
742 Paris, France True
743 Paris, France True
744 Paris, France True
745 Paris, France True
746 Paris, France True
747 Paris, France True
748 Paris, France True
749 Paris, France True
750 Paris, France True
751 Paris, France True
752 Paris, France True
753 Paris, France True
754 Paris, France True
755 Paris, France True
756 Paris, France True
757 Paris, France True
758 Paris, France True
759 Paris, France True
760 Paris, France True
761 London, England False
762 London, England True
763 London, England True
764 London, England True
765 London, England True
766 London, England True
767 London, England True
768 London, England True
769 London, England True
770 London, England True
771 London, England True
772 London, England True
773 London, England True
774 London, England True
775 London, England True
776 London, England True
777 London, England True
778 London, England True
779 London, England True
780 London, England True
781 London, England True
782 London, England True
783 London, England True
784 London, England True
785 London, England True
786 London, England True
787 London, England True
788 London, England True
789 London, England True
790 London, England True
791 London, England True
792 London, England True
793 London, England True
794 London, England True
795 London, England True
796 London, England True
797 London, England True
798 London, England True
799 London, England True
800 London, England True
801 London, England True
802 London, England True
803 London, England True
804 London, England True
805 London, England True
806 London, England True
807 London, England True
808 London, England True
809 London, England True
810 London, England True
811 London, England True
812 London, England True
813 London, England True
814 London, England True
815 London, England True
816 London, England True
817 London, England True
818 London, England True
819 London, England True
820 London, England True
821 London, England True
822 London, England True
823 London, England True
824 London, England True
825 London, England True
826 London, England True
827 London, England True
828 London, England True
829 London, England True
830 London, England True
831 London, England True
832 London, England True
833 London, England True
834 London, England True
835 London, England True
836 London, England True
837 London, England True
838 London, England True
839 London, England True
840 London, England True
841 London, England True
842 London, England True
843 London, England True
844 London, England True
845 London, England True
846 London, England True
847 London, England True
848 London, England True
849 London, England True
850 London, England True
851 London, England True
852 London, England True
853 London, England True
854 London, England True
855 London, England True
856 London, England True
857 London, England True
858 London, England True
859 London, England True
860 London, England True
861 London, England True
862 London, England True
863 London, England True
864 London, England True
865 London, England True
866 London, England True
867 London, England True
868 Cairnryan, Scotland False
869 Belfast, Northern Ireland False
870 Belfast, Northern Ireland True
871 Belfast, Northern Ireland True
872 Belfast, Northern Ireland True
873 Belfast, Northern Ireland True
874 Belfast, Northern Ireland True
875 Belfast, Northern Ireland True
876 Belfast, Northern Ireland True
877 Belfast, Northern Ireland True
878 Belfast, Northern Ireland True
879 Belfast, Northern Ireland True
880 Belfast, Northern Ireland True
881 Belfast, Northern Ireland True
882 Dublin, Ireland False
883 Dublin, Ireland True
884 Dublin, Ireland True
885 Dublin, Ireland True
886 Dublin, Ireland True
887 Dublin, Ireland True
888 Dublin, Ireland True
889 London, England False
890 Bournemouth, England False
891 Bournemouth, England True
892 Bournemouth, England True
893 Bournemouth, England True
894 Bournemouth, England True
895 Bournemouth, England True
896 Bournemouth, England True
897 Bournemouth, England True
898 Bournemouth, England True
899 Bournemouth, England True
900 Bournemouth, England True
901 Bournemouth, England True
902 Bournemouth, England True
903 Nottingham, England False
904 Nottingham, England True
905 Nottingham, England True
906 Nottingham, England True
907 Nottingham, England True
908 Nottingham, England True
909 Nottingham, England True
910 Nottingham, England True
911 Nottingham, England True
912 Nottingham, England True
913 Nottingham, England True
914 Nottingham, England True
915 Nottingham, England True
916 Nottingham, England True
917 Birmingham, England False
918 Birmingham, England True
919 Birmingham, England True
920 Birmingham, England True
921 Birmingham, England True
922 Birmingham, England True
923 Birmingham, England True
924 Birmingham, England True
925 Birmingham, England True
926 Birmingham, England True
927 Birmingham, England True
928 Birmingham, England True
929 Birmingham, England True
930 Birmingham, England True
931 Bristol, England False
932 Bristol, England True
933 Bristol, England True
934 Bristol, England True
935 Bristol, England True
936 Bristol, England True
937 Bristol, England True
938 Bristol, England True
939 Bristol, England True
940 Bristol, England True
941 Bristol, England True
942 Bristol, England True
943 Bristol, England True
944 Bristol, England True
945 London, England False
946 London, England True
947 London, England True
948 Copenhagen, Denmark False
949 Copenhagen, Denmark True
950 Copenhagen, Denmark True
951 Copenhagen, Denmark True
952 Copenhagen, Denmark True
953 Copenhagen, Denmark True
954 Copenhagen, Denmark True
955 Copenhagen, Denmark True
956 Copenhagen, Denmark True
957 Copenhagen, Denmark True
958 Copenhagen, Denmark True
959 Copenhagen, Denmark True
960 Copenhagen, Denmark True
961 Copenhagen, Denmark True
962 Copenhagen, Denmark True
963 Copenhagen, Denmark True
964 Copenhagen, Denmark True
965 Copenhagen, Denmark True
966 Copenhagen, Denmark True
967 Copenhagen, Denmark True
968 Copenhagen, Denmark True
969 Copenhagen, Denmark True
970 Copenhagen, Denmark True
971 Copenhagen, Denmark True
972 Copenhagen, Denmark True
973 Paris, France False
974 Paris, France True
975 Paris, France True
976 Paris, France True
977 Paris, France True
978 Paris, France True
979 Paris, France True
980 Vichy, France False
981 Vichy, France True
982 , France False
983 , France True
984 , France True
985 Juan-les-Pins, France False
986 , France False
987 Marseille?, France False
988 , France False
989 Nice, France False
990 , France False
991 , France True
992 Arachon, France False
993 Arachon, France True
994 , France False
995 Biarritz, France False
996 Biarritz, France True
997 Biarritz, France True
998 Biarritz, France True
999 Biarritz, France True
1000 ,  False
1001 Dax, France False
1002 ,  False
1003 ,  True
1004 ,  True
1005 ,  True
1006 ,  True
1007 ,  True
1008 ,  True
1009 ,  True
1010 ,  True
1011 ,  True
1012 ,  True
1013 ,  True
1014 ,  True
1015 Barcelona, Spain False
1016 Barcelona, Spain True
1017 Barcelona, Spain True
1018 Barcelona, Spain True
1019 Barcelona, Spain True
1020 Barcelona, Spain True
1021 Barcelona, Spain True
1022 Barcelona, Spain True
1023 Barcelona, Spain True
1024 Barcelona, Spain True
1025 Barcelona, Spain True
1026 Barcelona, Spain True
1027 Barcelona, Spain True
1028 Barcelona, Spain True
1029 Barcelona, Spain True
1030 Barcelona, Spain True
1031 Ventimiglia, Italy False
1032 Milan, Italy False
1033 Milan, Italy True
1034 Milan, Italy True
1035 Milan, Italy True
1036 Milan, Italy True
1037 Milan, Italy True
1038 Milan, Italy True
1039 Milan, Italy True
1040 Milan, Italy True
1041 Milan, Italy True
1042 Milan, Italy True
1043 Milan, Italy True
1044 Rome, Italy False
1045 Rome, Italy True
1046 Rome, Italy True
1047 Rome, Italy True
1048 Rome, Italy True
1049 Rome, Italy True
1050 Rome, Italy True
1051 Palermo, Italy False
1052 Palermo, Italy True
1053 Catania, Italy False
1054 Catania, Italy True
1055 Naples, Italy False
1056 Naples, Italy True
1057 Naples, Italy True
1058 Turin, Italy False
1059 Turin, Italy True
1060 Genoa, Italy False
1061 Genoa, Italy True
1062 Genoa, Italy True
1063 Genoa, Italy True
1064 Santa Margherita, Genoa, Italy False
1065 Santa Margherita, Genoa, Italy True
1066 Santa Margherita, Genoa, Italy True
1067 Santa Margherita, Genoa, Italy True
1068 Marseille, France False
1069 Marseille, France True
1070 Marseille, France True
1071 Marseille, France True
1072 Marseille, France True
1073 Marseille, France True
1074 Marseille, France True
1075 Marseille, France True
1076 Marseille, France True
1077 Marseille, France True
1078 Marseille, France True
1079 Marseille, France True
1080 Marseille, France True
1081 Marseille, France True
1082 Marseille, France True
1083 Marseille, France True
1084 Marseille, France True
1085 Marseille, France True
1086 Bern, Switzerland False
1087 Bern, Switzerland True
1088 Bern, Switzerland True
1089 Zurich, Switzerland False
1090 Zurich, Switzerland True
1091 Zurich, Switzerland True
1092 Zurich, Switzerland True
1093 ,  False
1094 Altreu, Switzerland False
1095 Lausanne, Switzerland False
1096 Basel, Switzerland False
1097 Basel, Switzerland True
1098 Rome, Italy False
1099 Rome, Italy True
1100 Sicily, Italy False
1101 Palermo, Italy False
1102 Palermo, Italy True
1103 Palermo, Italy True
1104 Catania, Italy False
1105 ,  False
1106 Bari, Italy False
1107 Bari, Italy True
1108 Naples, Italy False
1109 Naples, Italy True
1110 Naples, Italy True
1111 Naples, Italy True
1112 Livorno, Italy False
1113 Florence, Italy False
1114 Florence, Italy True
1115 Trieste, Italy False
1116 Trieste, Italy True
1117 Trieste, Italy True
1118 Padova, Italy False
1119 Brescia, Italy False
1120 Varese, Italy False
1121 Varese, Italy True
1122 Bergamo, Italy False
1123 Bergamo, Italy True
1124 Verona, Italy False
1125 Verona, Italy True
1126 Bologna, Italy False
1127 Bologna, Italy True
1128 Bologna, Italy True
1129 ,  False
1130 ,  True
1131 ,  True
1132 ,  True
1133 ,  True
1134 Rome, Italy False
1135 Rome, Italy True
1136 Rome, Italy True
1137 Rome, Italy True
1138 Rome, Italy True
1139 Rome, Italy True
1140 ,  False
1141 Paris, France False
1142 Paris, France True
1143 Paris, France True
1144 Paris, France True
1145 Paris, France True
1146 Paris, France True
1147 Paris, France True
1148 Paris, France True
1149 Paris, France True
1150 Paris, France True
1151 Paris, France True
1152 Paris, France True
1153 Paris, France True
1154 Paris, France True
1155 Paris, France True
1156 Paris, France True
1157 Paris, France True
1158 Paris, France True
1159 Paris, France True
1160 Paris, France True
1161 Paris, France True
1162 Paris, France True
1163 Paris, France True
1164 Paris, France True
1165 Paris, France True
1166 Paris, France True
1167 Paris, France True
1168 Paris, France True
1169 Paris, France True
1170 Paris, France True
1171 Paris, France True
1172 Paris, France True
1173 Paris, France True
1174 Paris, France True
1175 Paris, France True
1176 Paris, France True
1177 Paris, France True
1178 Paris, France True
1179 Paris, France True
1180 ,  False
1181 ,  True
1182 ,  True
1183 ,  True
1184 ,  True
1185 Bordeaux, France False
1186 Bordeaux, France True
1187 ,  False
1188 Paris, France False
1189 Paris, France True
1190 Paris, France True
1191 Paris, France True
1192 Paris, France True
1193 Paris, France True
1194 Paris, France True
1195 Paris, France True
1196 Paris, France True
1197 ,  False
1198 ,  True
1199 ,  True
1200 ,  True
1201 ,  True
1202 ,  True
1203 ,  True
1204 ,  True
1205 Oran, Algeria False
1206 Oran, Algeria True
1207 ,  False
1208 ,  True
1209 Casablanca, Morocco False
1210 Casablanca, Morocco True
1211 ,  False
1212 ,  True
1213 ,  True
1214 ,  True
1215 ,  True
1216 ,  True
1217 ,  True
1218 Paris, France False
1219 Paris, France True
1220 New York City, USA False
1221 New York City, USA True
1222 Chicago, Illinois False
1223 ,  False
1224 ,  True
1225 Joliet, Illinois False
1226 ,  False
1227 ,  True
1228 ,  True
1229 ,  True
1230 ,  True
1231 ,  True
1232 ,  True
1233 Hollywood, USA False
1234 Hollywood, USA True
1235 Hollywood, USA True
1236 Hollywood, USA True
1237 Hollywood, USA True
1238 Hollywood, USA True
1239 Hollywood, USA True
1240 Hollywood, USA True
1241 Hollywood, USA True
1242 Hollywood, USA True
1243 Hollywood, USA True
1244 Hollywood, USA True
1245 Hollywood, USA True
1246 Hollywood, USA True
1247 Hollywood, USA True
1248 Hollywood, USA True
1249 Hollywood, USA True
1250 Hollywood, USA True
1251 Hollywood, USA True
1252 Hollywood, USA True
1253 Hollywood, USA True
1254 Hollywood, USA True
1255 San Francisco, USA False
1256 San Francisco, USA True
1257 San Francisco, USA True
1258 San Francisco, USA True
1259 San Francisco, USA True
1260 San Francisco, USA True
1261 San Francisco, USA True
1262 San Francisco, USA True
1263 San Francisco, USA True
1264 San Francisco, USA True
1265 San Francisco, USA True
1266 San Francisco, USA True
1267 San Francisco, USA True
1268 San Francisco, USA True
1269 San Francisco, USA True
1270 San Francisco, USA True
1271 San Francisco, USA True
1272 San Francisco, USA True
1273 San Francisco, USA True
1274 San Francisco, USA True
1275 San Francisco, USA True
1276 San Francisco, USA True
1277 San Francisco, USA True
1278 Las Vegas, USA False
1279 Las Vegas, USA True
1280 Las Vegas, USA True
1281 Las Vegas, USA True
1282 Las Vegas, USA True
1283 Las Vegas, USA True
1284 Las Vegas, USA True
1285 Las Vegas, USA True
1286 Las Vegas, USA True
1287 Las Vegas, USA True
1288 Hollywood, USA False
1289 Las Vegas, USA False
1290 Las Vegas, USA True
1291 Las Vegas, USA True
1292 Hollywood, USA False
1293 Hollywood, USA True
1294 Hollywood, USA True
1295 Hollywood, USA True
1296 Hollywood, USA True
1297 Hollywood, USA True
1298 Hollywood, USA True
1299 Hollywood, USA True
1300 Hollywood, USA True
1301 Reno, USA False
1302 Reno, USA True
1303 Reno, USA True
1304 Reno, USA True
1305 Reno, USA True
1306 Hollywood, USA False
1307 Reno, USA False
1308 Reno, USA True
1309 Reno, USA True
1310 Reno, USA True
1311 Reno, USA True
1312 Reno, USA True
1313 Reno, USA True

1314 Reno, USA True
1315 Reno, USA True
1316 Reno, USA True
1317 Hollywood, USA False
1318 Hollywood, USA True
1319 Hollywood, USA True
1320 Hollywood, USA True
1321 Hollywood, USA True
1322 Hollywood, USA True
1323 Hollywood, USA True
1324 Hollywood, USA True
1325 Hollywood, USA True
1326 Hollywood, USA True
1327 Hollywood, USA True
1328 Hollywood, USA True
1329 Hollywood, USA True
1330 Hollywood, USA True
1331 Hollywood, USA True
1332 Hollywood, USA True
1333 Hollywood, USA True
1334 Hollywood, USA True
1335 Hollywood, USA True
1336 Hollywood, USA True
1337 Hollywood, USA True
1338 Hollywood, USA True
1339 Hollywood, USA True
1340 Hollywood, USA True
1341 Hollywood, USA True
1342 Hollywood, USA True
1343 Hollywood, USA True
1344 Hollywood, USA True
1345 Hollywood, USA True
1346 Hollywood, USA True
1347 Vancouver, Canada False
1348 Vancouver, Canada True
1349 Vancouver, Canada True
1350 Vancouver, Canada True
1351 Vancouver, Canada True
1352 Vancouver, Canada True
1353 Vancouver, Canada True
1354 Vancouver, Canada True
1355 Vancouver, Canada True
1356 Vancouver, Canada True
1357 Vancouver, Canada True
1358 Vancouver, Canada True
1359 Vancouver, Canada True
1360 Vancouver, Canada True
1361 Vancouver, Canada True
1362 ,  False
1363 Crystal Bay, NV, USA False
1364 Crystal Bay, NV, USA True
1365 Crystal Bay, NV, USA True
1366 Crystal Bay, NV, USA True
1367 Crystal Bay, NV, USA True
1368 Crystal Bay, NV, USA True
1369 Crystal Bay, NV, USA True
1370 Crystal Bay, NV, USA True
1371 Crystal Bay, NV, USA True
1372 Crystal Bay, NV, USA True
1373 Hollywood, USA False
1374 Hollywood, USA True
1375 Hollywood, USA True
1376 Hollywood, USA True
1377 Hollywood, USA True
1378 Hollywood, USA True
1379 Hollywood, USA True
1380 Hollywood, USA True
1381 Hollywood, USA True
1382 Hollywood, USA True
1383 Hollywood, USA True
1384 Hollywood, USA True
1385 Hollywood, USA True
1386 Hollywood, USA True
1387 Hollywood, USA True
1388 Hollywood, USA True
1389 Hollywood, USA True
1390 Hollywood, USA True
1391 Hollywood, USA True
1392 Hollywood, USA True
1393 Hollywood, USA True
1394 Hollywood, USA True
1395 Hollywood, USA True
1396 Hollywood, USA True
1397 Hollywood, USA True
1398 Hollywood, USA True
1399 Hollywood, USA True
1400 Hollywood, USA True
1401 Hollywood, USA True
1402 Hollywood, USA True
1403 Hollywood, USA True
1404 Hollywood, USA True
1405 Hollywood, USA True
1406 Hollywood, USA True
1407 Hollywood, USA True
1408 Hollywood, USA True
1409 Hollywood, USA True
1410 Hollywood, USA True
1411 Hollywood, USA True
1412 ,  False
1413 ,  True
1414 Havana, Cuba False
1415 Havana, Cuba True
1416 Havana, Cuba True
1417 ,  False
1418 ,  True
1419 Los Angeles, USA False
1420 Los Angeles, USA True
1421 Los Angeles, USA True
1422 Los Angeles, USA True
1423 Los Angeles, USA True
1424 Los Angeles, USA True
1425 Los Angeles, USA True
1426 Los Angeles, USA True
1427 Los Angeles, USA True
1428 Los Angeles, USA True
1429 ,  False
1430 ,  True
1431 ,  True
1432 ,  True
1433 ,  True
1434 ,  True
1435 ,  True
1436 ,  True
1437 ,  True
1438 San Francisco, USA False
1439 San Francisco, USA True
1440 San Francisco, USA True
1441 San Francisco , USA False
1442 ,  False
1443 ,  True
1444 ,  True
1445 ,  True
1446 ,  True
1447 Beverly Hills, USA False
1448 ,  False
1449 ,  True
1450 ,  True
1451 ,  True
1452 ,  True
1453 ,  True
1454 ,  True
1455 ,  True
1456 New York, USA False
1457 Paris, France False
1458 ,  False
1459 ,  True
1460 Rome, Italy False
1461 Rome, Italy True
1462 Rome, Italy True
1463 Rome, Italy True
1464 Rome, Italy True
1465 Rome, Italy True
1466 Rome, Italy True
1467 Rome, Italy True
1468 Rome, Italy True
1469 Rome, Italy True
1470 Rome, Italy True
1471 Rome, Italy True
1472 Rome, Italy True
1473 Rome, Italy True
1474 Rome, Italy True
1475 Rome, Italy True
1476 Rome, Italy True
1477 Rome, Italy True
1478 Rome, Italy True
1479 Rome, Italy True
1480 Rome, Italy True
1481 Rome, Italy True
1482 Rome, Italy True
1483 Rome, Italy True
1484 Rome, Italy True
1485 Rome, Italy True
1486 Rome, Italy True
1487 Rome, Italy True
1488 Rome, Italy True
1489 Rome, Italy True
1490 Rome, Italy True
1491 Rome, Italy True
1492 Rome, Italy True
1493 Rome, Italy True
1494 Rome, Italy True
1495 Rome, Italy True
1496 Rome, Italy True
1497 Rome, Italy True
1498 Rome, Italy True

In [124]:
def trip_duration(df, column):
    count = 0
    results = {}
    for i, v in df.iterrows():
        index = i+1

        if v['same'] != False:
            count += 1
            print(i, v['Date'], v[column])
        else:
            result = {df[column][i-1]: count}
            # just one entry is 1
            if result[df[column][i-1]] == 0:
                result[df[column][i-1]] = 1
            print(result)
            #index of trips dict set here
            results[len(results)] = result
            count = 0
    return results
    #     print(i+1, v['City, Country'], v['same'])

In [152]:
trips

{0: {'Paris': 30},
 1: {'Cairo': 4},
 2: {'Rome': 1},
 3: {'Turin': 1},
 4: {'Genoa': 3},
 5: {nan: 1},
 6: {'Naples': 1},
 7: {'Rome': 8},
 8: {nan: 1},
 9: {'Florence': 3},
 10: {'Bologna': 1},
 11: {'Milan': 19},
 12: {'Venice': 2},
 13: {'Milan': 1},
 14: {'Piacenza': 1},
 15: {'Brescia': 1},
 16: {'Biella': 1},
 17: {'Genoa': 1},
 18: {'Milan': 1},
 19: {'Paris': 11},
 20: {'New York City': 55},
 21: {'Belem': 1},
 22: {'Recife': 5},
 23: {'Rio de Janeiro': 26},
 24: {'Sao Paulo': 18},
 25: {'Rio de Janeiro': 15},
 26: {'Montevideo': 15},
 27: {'Buenos Aires': 74},
 28: {nan: 9},
 29: {'Santiago': 17},
 30: {'Buenos Aires': 1},
 31: {'Mar del Plata': 21},
 32: {'Buenos Aires': 1},
 33: {'Lima': 23},
 34: {'Quito': 3},
 35: {'Cali': 1},
 36: {'Bogota': 14},
 37: {'Medellin': 1},
 38: {'Barranquilla': 2},
 39: {'Cartagena': 1},
 40: {'Barranquilla': 2},
 41: {'Caracas': 11},
 42: {'Kingston': 1},
 43: {'Petion-Ville': 4},
 44: {'Kingston': 26},
 45: {'Port au Prince': 81},
 46: {'Port-au-Prince': 45},
 47: {'Mexico City': 1},
 48: {'Guadalajara': 10},
 49: {'Mexico City': 1},
 50: {'Las Vegas': 17},
 51: {'Reno': 8},
 52: {nan: 7},
 53: {'Hollywood': 10},
 54: {nan: 4},
 55: {'New York': 2},
 56: {nan: 1},
 57: {'New York': 1},
 58: {'Gander': 1},
 59: {'Paris': 88},
 60: {'London': 106},
 61: {'Cairnryan': 1},
 62: {'Belfast': 12},
 63: {'Dublin': 6},
 64: {'London': 1},
 65: {'Bournemouth': 12},
 66: {'Nottingham': 13},
 67: {'Birmingham': 13},
 68: {'Bristol': 13},
 69: {'London': 2},
 70: {'Copenhagen': 24},
 71: {'Paris': 6},
 72: {'Vichy': 1},
 73: {nan: 2},
 74: {'Juan-les-Pins': 1},
 75: {nan: 1},
 76: {'Marseille?': 1},
 77: {nan: 1},
 78: {'Nice': 1},
 79: {nan: 1},
 80: {'Arachon': 1},
 81: {nan: 1},
 82: {'Biarritz': 4},
 83: {nan: 1},
 84: {'Dax': 1},
 85: {nan: 12},
 86: {'Barcelona': 15},
 87: {'Ventimiglia': 1},
 88: {'Milan': 11},
 89: {'Rome': 6},
 90: {'Palermo': 1},
 91: {'Catania': 1},
 92: {'Naples': 2},
 93: {'Turin': 1},
 94: {'Genoa': 3},
 95: {'Santa Margherita, Genoa': 3},
 96: {'Marseille': 17},
 97: {'Bern': 2},
 98: {'Zurich': 3},
 99: {nan: 1},
 100: {'Altreu': 1},
 101: {'Lausanne': 1},
 102: {'Basel': 1},
 103: {'Rome': 1},
 104: {'Sicily': 1},
 105: {'Palermo': 2},
 106: {'Catania': 1},
 107: {nan: 1},
 108: {'Bari': 1},
 109: {'Naples': 3},
 110: {'Livorno': 1},
 111: {'Florence': 1},
 112: {'Trieste': 2},
 113: {'Padova': 1},
 114: {'Brescia': 1},
 115: {'Varese': 1},
 116: {'Bergamo': 1},
 117: {'Verona': 1},
 118: {'Bologna': 2},
 119: {nan: 4},
 120: {'Rome': 5},
 121: {nan: 1},
 122: {'Paris': 38},
 123: {nan: 4},
 124: {'Bordeaux': 1},
 125: {nan: 1},
 126: {'Paris': 8},
 127: {nan: 7},
 128: {'Oran': 1},
 129: {nan: 1},
 130: {'Casablanca': 1},
 131: {nan: 6},
 132: {'Paris': 1},
 133: {'New York City': 1},
 134: {'Chicago': 1},
 135: {nan: 1},
 136: {'Joliet': 1},
 137: {nan: 6},
 138: {'Hollywood': 21},
 139: {'San Francisco': 22},
 140: {'Las Vegas': 9},
 141: {'Hollywood': 1},
 142: {'Las Vegas': 2},
 143: {'Hollywood': 8},
 144: {'Reno': 4},
 145: {'Hollywood': 1},
 146: {'Reno': 9},
 147: {'Hollywood': 29},
 148: {'Vancouver': 14},
 149: {nan: 1},
 150: {'Crystal Bay, NV': 9},
 151: {'Hollywood': 38},
 152: {nan: 1},
 153: {'Havana': 2},
 154: {nan: 1},
 155: {'Los Angeles': 9},
 156: {nan: 8},
 157: {'San Francisco': 2},
 158: {'San Francisco ': 1},
 159: {nan: 4},
 160: {'Beverly Hills': 1},
 161: {nan: 7},
 162: {'New York': 1},
 163: {'Paris': 1},
 164: {nan: 1}}

In [128]:
trips

{0: {'Paris': 30},
 1: {'Cairo': 4},
 2: {'Rome': 1},
 3: {'Turin': 1},
 4: {'Genoa': 3},
 5: {nan: 1},
 6: {'Naples': 1},
 7: {'Rome': 8},
 8: {nan: 1},
 9: {'Florence': 3},
 10: {'Bologna': 1},
 11: {'Milan': 19},
 12: {'Venice': 2},
 13: {'Milan': 1},
 14: {'Piacenza': 1},
 15: {'Brescia': 1},
 16: {'Biella': 1},
 17: {'Genoa': 1},
 18: {'Milan': 1},
 19: {'Paris': 11},
 20: {'New York City': 55},
 21: {'Belem': 1},
 22: {'Recife': 5},
 23: {'Rio de Janeiro': 26},
 24: {'Sao Paulo': 18},
 25: {'Rio de Janeiro': 15},
 26: {'Montevideo': 15},
 27: {'Buenos Aires': 74},
 28: {nan: 9},
 29: {'Santiago': 17},
 30: {'Buenos Aires': 1},
 31: {'Mar del Plata': 21},
 32: {'Buenos Aires': 1},
 33: {'Lima': 23},
 34: {'Quito': 3},
 35: {'Cali': 1},
 36: {'Bogota': 14},
 37: {'Medellin': 1},
 38: {'Barranquilla': 2},
 39: {'Cartagena': 1},
 40: {'Barranquilla': 2},
 41: {'Caracas': 11},
 42: {'Kingston': 1},
 43: {'Petion-Ville': 4},
 44: {'Kingston': 26},
 45: {'Port au Prince': 81},
 46: {'Port-au-Prince': 45},
 47: {'Mexico City': 1},
 48: {'Guadalajara': 10},
 49: {'Mexico City': 1},
 50: {'Las Vegas': 17},
 51: {'Reno': 8},
 52: {nan: 7},
 53: {'Hollywood': 10},
 54: {nan: 4},
 55: {'New York': 2},
 56: {nan: 1},
 57: {'New York': 1},
 58: {'Gander': 1},
 59: {'Paris': 88},
 60: {'London': 106},
 61: {'Cairnryan': 1},
 62: {'Belfast': 12},
 63: {'Dublin': 6},
 64: {'London': 1},
 65: {'Bournemouth': 12},
 66: {'Nottingham': 13},
 67: {'Birmingham': 13},
 68: {'Bristol': 13},
 69: {'London': 2},
 70: {'Copenhagen': 24},
 71: {'Paris': 6},
 72: {'Vichy': 1},
 73: {nan: 2},
 74: {'Juan-les-Pins': 1},
 75: {nan: 1},
 76: {'Marseille?': 1},
 77: {nan: 1},
 78: {'Nice': 1},
 79: {nan: 1},
 80: {'Arachon': 1},
 81: {nan: 1},
 82: {'Biarritz': 4},
 83: {nan: 1},
 84: {'Dax': 1},
 85: {nan: 12},
 86: {'Barcelona': 15},
 87: {'Ventimiglia': 1},
 88: {'Milan': 11},
 89: {'Rome': 6},
 90: {'Palermo': 1},
 91: {'Catania': 1},
 92: {'Naples': 2},
 93: {'Turin': 1},
 94: {'Genoa': 3},
 95: {'Santa Margherita, Genoa': 3},
 96: {'Marseille': 17},
 97: {'Bern': 2},
 98: {'Zurich': 3},
 99: {nan: 1},
 100: {'Altreu': 1},
 101: {'Lausanne': 1},
 102: {'Basel': 1},
 103: {'Rome': 1},
 104: {'Sicily': 1},
 105: {'Palermo': 2},
 106: {'Catania': 1},
 107: {nan: 1},
 108: {'Bari': 1},
 109: {'Naples': 3},
 110: {'Livorno': 1},
 111: {'Florence': 1},
 112: {'Trieste': 2},
 113: {'Padova': 1},
 114: {'Brescia': 1},
 115: {'Varese': 1},
 116: {'Bergamo': 1},
 117: {'Verona': 1},
 118: {'Bologna': 2},
 119: {nan: 4},
 120: {'Rome': 5},
 121: {nan: 1},
 122: {'Paris': 38},
 123: {nan: 4},
 124: {'Bordeaux': 1},
 125: {nan: 1},
 126: {'Paris': 8},
 127: {nan: 7},
 128: {'Oran': 1},
 129: {nan: 1},
 130: {'Casablanca': 1},
 131: {nan: 6},
 132: {'Paris': 1},
 133: {'New York City': 1},
 134: {'Chicago': 1},
 135: {nan: 1},
 136: {'Joliet': 1},
 137: {nan: 6},
 138: {'Hollywood': 21},
 139: {'San Francisco': 22},
 140: {'Las Vegas': 9},
 141: {'Hollywood': 1},
 142: {'Las Vegas': 2},
 143: {'Hollywood': 8},
 144: {'Reno': 4},
 145: {'Hollywood': 1},
 146: {'Reno': 9},
 147: {'Hollywood': 29},
 148: {'Vancouver': 14},
 149: {nan: 1},
 150: {'Crystal Bay, NV': 9},
 151: {'Hollywood': 38},
 152: {nan: 1},
 153: {'Havana': 2},
 154: {nan: 1},
 155: {'Los Angeles': 9},
 156: {nan: 8},
 157: {'San Francisco': 2},
 158: {'San Francisco ': 1},
 159: {nan: 4},
 160: {'Beverly Hills': 1},
 161: {nan: 7},
 162: {'New York': 1},
 163: {'Paris': 1},
 164: {nan: 1}}

In [138]:
def count_return_trips(trips):
    vals = {}                       # A dictonary to store how often each value occurs.
    for i in trips.values():
      for j in set(i):              # Convert to a set to remove duplicates
        vals[j] = 1 + vals.get(j,0) # If we've seen this value iterate the count
                                    # Otherwise we get the default of 0 and iterate it
    # sort returned values
    return sorted(vals.items(), key= lambda x: x[1], reverse=True)

In [139]:
count_return_trips(trips)

[(nan, 31),
 ('Paris', 8),
 ('Hollywood', 7),
 ('Rome', 5),
 ('Milan', 4),
 ('Genoa', 3),
 ('Naples', 3),
 ('Buenos Aires', 3),
 ('Las Vegas', 3),
 ('Reno', 3),
 ('New York', 3),
 ('London', 3),
 ('Turin', 2),
 ('Florence', 2),
 ('Bologna', 2),
 ('Brescia', 2),
 ('New York City', 2),
 ('Rio de Janeiro', 2),
 ('Barranquilla', 2),
 ('Kingston', 2),
 ('Mexico City', 2),
 ('Palermo', 2),
 ('Catania', 2),
 ('San Francisco', 2),
 ('Cairo', 1),
 ('Venice', 1),
 ('Piacenza', 1),
 ('Biella', 1),
 ('Belem', 1),
 ('Recife', 1),
 ('Sao Paulo', 1),
 ('Montevideo', 1),
 ('Santiago', 1),
 ('Mar del Plata', 1),
 ('Lima', 1),
 ('Quito', 1),
 ('Cali', 1),
 ('Bogota', 1),
 ('Medellin', 1),
 ('Cartagena', 1),
 ('Caracas', 1),
 ('Petion-Ville', 1),
 ('Port au Prince', 1),
 ('Port-au-Prince', 1),
 ('Guadalajara', 1),
 ('Gander', 1),
 ('Cairnryan', 1),
 ('Belfast', 1),
 ('Dublin', 1),
 ('Bournemouth', 1),
 ('Nottingham', 1),
 ('Birmingham', 1),
 ('Bristol', 1),
 ('Copenhagen', 1),
 ('Vichy', 1),
 ('Juan-les-Pins', 1),
 ('Marseille?', 1),
 ('Nice', 1),
 ('Arachon', 1),
 ('Biarritz', 1),
 ('Dax', 1),
 ('Barcelona', 1),
 ('Ventimiglia', 1),
 ('Santa Margherita, Genoa', 1),
 ('Marseille', 1),
 ('Bern', 1),
 ('Zurich', 1),
 ('Altreu', 1),
 ('Lausanne', 1),
 ('Basel', 1),
 ('Sicily', 1),
 ('Bari', 1),
 ('Livorno', 1),
 ('Trieste', 1),
 ('Padova', 1),
 ('Varese', 1),
 ('Bergamo', 1),
 ('Verona', 1),
 ('Bordeaux', 1),
 ('Oran', 1),
 ('Casablanca', 1),
 ('Chicago', 1),
 ('Joliet', 1),
 ('Vancouver', 1),
 ('Crystal Bay, NV', 1),
 ('Havana', 1),
 ('Los Angeles', 1),
 ('San Francisco ', 1),
 ('Beverly Hills', 1)]

In [151]:
trips.items()

TypeError: 'dict_items' object does not support indexing