In [21]:
import pandas as pd
import numpy as np
from collections import Counter

In [159]:
#read in file to count
df = pd.read_csv('g3.csv')

In [160]:
df

,Unnamed: 0,Unnamed: 0.1,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same,location
0,0,0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
1,1,1,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,NaN
2,2,2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.856614,2.352222,True,NaN
3,3,3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.856614,2.352222,True,NaN
4,4,4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,48.856614,2.352222,True,"Paris,France"
5,5,5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,48.856614,2.352222,True,NaN
6,6,6,1950-01-07,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,"Paris,France"
7,7,7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
8,8,8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
9,9,9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
10,10,10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
11,11,11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
12,12,12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
13,13,13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
14,14,14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
15,15,15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
16,16,16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
17,17,17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
18,18,18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
19,19,19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
20,20,20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
21,21,21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
22,22,22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
23,23,23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
24,24,24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
25,25,25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
26,26,26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7",48.856614,2.352222,True,NaN
27,27,27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
28,28,28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
29,29,29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,48.856614,2.352222,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1432,1432,1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1433,1433,1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1434,1434,1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1435,1435,1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1436,1436,1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1437,1437,1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1438,1438,1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1439,1439,1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,41.902784,12.496365,True,NaN
1440,1440,1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1441,1441,1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1442,1442,1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1443,1443,1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,NaN
1444,1444,1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1445,1445,1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1446,1446,1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1447,1447,1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,NaN
1448,1448,1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1449,1449,1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1450,1450,1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1451,1451,1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1452,1452,1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1453,1453,1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1454,1454,1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1455,1455,1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1456,1456,1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1457,1457,1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1458,1458,1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1459,1459,1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1460,1460,1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN

In [161]:
# drop no city values
df = df.dropna(subset=['city_1']).reset_index()

In [162]:
"""
Loop through data and count two things:

Length of stay = number of consecutive days in same city, call it a single 'trip' (may indicate success in an area)

# of visits to an city = number of trips to a city ( may indicate prefrence )
"""

def compare_previous(df, column):
    """
    compare previous row for change in column value
    """
    return df[column].eq(df[column].shift())

def count_duration(trips):
    """
    count number of rows column value stays the same
    """
    return sorted(trips, key= lambda x: x[1], reverse=True)

def count_visits(trips):
    counts = Counter(elem[0] for elem in trips)
    visits = counts.most_common()
    return visits

def trip_duration_count(df, column):
    """
    Initial loop through data counting trips and their date ranges
    
    """
    count = 0
    results = []
    for i, v in df.iterrows():
        min_date = df['date'][i]
        lat = v['lat']
        lng = v['lng']
        print(lat)
        print(lng)

        if v['same'] != False:
            count += 1
            max_date = df['date'][count]
            
            print(i)
        else:
#             result = {df[column][i-1]: count}
            max_date = df['date'][i-1]
            min_date = df['date'][i-count]
            
            result = (df[column][i-1] , count, min_date, max_date, df['lat'][i-1], df['lng'][i-1] )
            # just one entry is 1
            if result[1] == 0:
#                 result[df[column][i-1]] = 1
                result = (df[column][i-1] , count+1, min_date, max_date, df['lat'][i-1], df['lng'][i-1])
#             print(result)
            #index of trips dict set here
#             results[len(results)] = result
            results.append(result)
            count = 0
#         print(v['same'], min_date, max_date)
    return results
    #     print(i+1, v['City, Country'], v['same'])
    

df['same'] = compare_previous(df, 'city_1')
#change first entry value to true
df['same'][0] = True

trips = trip_duration_count(df, 'city_1')
durations = count_duration(trips)
visits = count_visits(trips)

/usr/lib/python3.6/site-packages/ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

48.856614
2.3522218999999995
0
48.856614
2.3522218999999995
1
48.856614
2.3522218999999995
2
48.856614
2.3522218999999995
3
48.856614
2.3522218999999995
4
48.856614
2.3522218999999995
5
48.856614
2.3522218999999995
6
48.856614
2.3522218999999995
7
48.856614
2.3522218999999995
8
48.856614
2.3522218999999995
9
48.856614
2.3522218999999995
10
48.856614
2.3522218999999995
11
48.856614
2.3522218999999995
12
48.856614
2.3522218999999995
13
48.856614
2.3522218999999995
14
48.856614
2.3522218999999995
15
48.856614
2.3522218999999995
16
48.856614
2.3522218999999995
17
48.856614
2.3522218999999995
18
48.856614
2.3522218999999995
19
48.856614
2.3522218999999995
20
48.856614
2.3522218999999995
21
48.856614
2.3522218999999995
22
48.856614
2.3522218999999995
23
48.856614
2.3522218999999995
24
48.856614
2.3522218999999995
25
48.856614
2.3522218999999995
26
48.856614
2.3522218999999995
27
48.856614
2.3522218999999995
28
48.856614
2.3522218999999995
29
30.0444196
31.235711600000005
30.0444196
31.235711600000005
31
30.0444196
31.235711600000005
32
30.0444196
31.235711600000005
33
30.0444196
31.235711600000005
34
41.90278350000001
12.4963655
45.070312
7.6868564999999975
45.070312
7.6868564999999975
37
44.4056499
8.946256
44.4056499
8.946256
39
40.85177460000001
14.2681244
40.85177460000001
14.2681244
41
41.90278350000001
12.4963655
41.90278350000001
12.4963655
43
41.90278350000001
12.4963655
44
41.90278350000001
12.4963655
45
41.90278350000001
12.4963655
46
41.90278350000001
12.4963655
47
41.90278350000001
12.4963655
48
41.90278350000001
12.4963655
49
41.90278350000001
12.4963655
50
43.7695604
11.2558136
43.7695604
11.2558136
52
43.7695604
11.2558136
53
43.7695604
11.2558136
54
44.494887
11.3426162
44.494887
11.3426162
56
45.4642035
9.189982
45.4642035
9.189982
58
45.4642035
9.189982
59
45.4642035
9.189982
60
45.4642035
9.189982
61
45.4642035
9.189982
62
45.4642035
9.189982
63
45.4642035
9.189982
64
45.4642035
9.189982
65
45.4642035
9.189982
66
45.4642035
9.189982
67
45.4642035
9.189982
68
45.4642035
9.189982
69
45.4642035
9.189982
70
45.4642035
9.189982
71
45.4642035
9.189982
72
45.4642035
9.189982
73
45.4642035
9.189982
74
45.4642035
9.189982
75
45.4642035
9.189982
76
45.4408474
12.3155151
45.4408474
12.3155151
78
45.4408474
12.3155151
79
45.4642035
9.189982
45.0526206
9.6929845
45.5415526
10.2118019
45.562884200000006
8.0583397
44.4056499
8.946256
45.4642035
9.189982
48.856614
2.3522218999999995
48.856614
2.3522218999999995
87
48.856614
2.3522218999999995
88
48.856614
2.3522218999999995
89
48.856614
2.3522218999999995
90
48.856614
2.3522218999999995
91
48.856614
2.3522218999999995
92
48.856614
2.3522218999999995
93
48.856614
2.3522218999999995
94
48.856614
2.3522218999999995
95
48.856614
2.3522218999999995
96
48.856614
2.3522218999999995
97
40.7127753
-74.0059728
40.7127753
-74.0059728
99
40.7127753
-74.0059728
100
40.7127753
-74.0059728
101
40.7127753
-74.0059728
102
40.7127753
-74.0059728
103
40.7127753
-74.0059728
104
40.7127753
-74.0059728
105
40.7127753
-74.0059728
106
40.7127753
-74.0059728
107
40.7127753
-74.0059728
108
40.7127753
-74.0059728
109
40.7127753
-74.0059728
110
40.7127753
-74.0059728
111
40.7127753
-74.0059728
112
40.7127753
-74.0059728
113
40.7127753
-74.0059728
114
40.7127753
-74.0059728
115
40.7127753
-74.0059728
116
40.7127753
-74.0059728
117
40.7127753
-74.0059728
118
40.7127753
-74.0059728
119
40.7127753
-74.0059728
120
40.7127753
-74.0059728
121
40.7127753
-74.0059728
122
40.7127753
-74.0059728
123
40.7127753
-74.0059728
124
40.7127753
-74.0059728
125
40.7127753
-74.0059728
126
40.7127753
-74.0059728
127
40.7127753
-74.0059728
128
40.7127753
-74.0059728
129
40.7127753
-74.0059728
130
40.7127753
-74.0059728
131
40.7127753
-74.0059728
132
40.7127753
-74.0059728
133
40.7127753
-74.0059728
134
40.7127753
-74.0059728
135
40.7127753
-74.0059728
136
40.7127753
-74.0059728
137
40.7127753
-74.0059728
138
40.7127753
-74.0059728
139
40.7127753
-74.0059728
140
40.7127753
-74.0059728
141
40.7127753
-74.0059728
142
40.7127753
-74.0059728
143
40.7127753
-74.0059728
144
40.7127753
-74.0059728
145
40.7127753
-74.0059728
146
40.7127753
-74.0059728
147
40.7127753
-74.0059728
148
40.7127753
-74.0059728
149
40.7127753
-74.0059728
150
40.7127753
-74.0059728
151
40.7127753
-74.0059728
152
40.7127753
-74.0059728
153
-1.4557292
-48.4901785
-1.4557292
-48.4901785
155
-8.0522404
-34.9286096
-8.0522404
-34.9286096
157
-8.0522404
-34.9286096
158
-8.0522404
-34.9286096
159
-8.0522404
-34.9286096
160
-8.0522404
-34.9286096
161
-22.9068467
-43.1728965
-22.9068467
-43.1728965
163
-22.9068467
-43.1728965
164
-22.9068467
-43.1728965
165
-22.9068467
-43.1728965
166
-22.9068467
-43.1728965
167
-22.9068467
-43.1728965
168
-22.9068467
-43.1728965
169
-22.9068467
-43.1728965
170
-22.9068467
-43.1728965
171
-22.9068467
-43.1728965
172
-22.9068467
-43.1728965
173
-22.9068467
-43.1728965
174
-22.9068467
-43.1728965
175
-22.9068467
-43.1728965
176
-22.9068467
-43.1728965
177
-22.9068467
-43.1728965
178
-22.9068467
-43.1728965
179
-22.9068467
-43.1728965
180
-22.9068467
-43.1728965
181
-22.9068467
-43.1728965
182
-22.9068467
-43.1728965
183
-22.9068467
-43.1728965
184
-22.9068467
-43.1728965
185
-22.9068467
-43.1728965
186
-22.9068467
-43.1728965
187
-22.9068467
-43.1728965
188
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
190
-23.5505199
-46.63330939999999
191
-23.5505199
-46.63330939999999
192
-23.5505199
-46.63330939999999
193
-23.5505199
-46.63330939999999
194
-23.5505199
-46.63330939999999
195
-23.5505199
-46.63330939999999
196
-23.5505199
-46.63330939999999
197
-23.5505199
-46.63330939999999
198
-23.5505199
-46.63330939999999
199
-23.5505199
-46.63330939999999
200
-23.5505199
-46.63330939999999
201
-23.5505199
-46.63330939999999
202
-23.5505199
-46.63330939999999
203
-23.5505199
-46.63330939999999
204
-23.5505199
-46.63330939999999
205
-23.5505199
-46.63330939999999
206
-23.5505199
-46.63330939999999
207
-22.9068467
-43.1728965
-22.9068467
-43.1728965
209
-22.9068467
-43.1728965
210
-22.9068467
-43.1728965
211
-22.9068467
-43.1728965
212
-22.9068467
-43.1728965
213
-22.9068467
-43.1728965
214
-22.9068467
-43.1728965
215
-22.9068467
-43.1728965
216
-22.9068467
-43.1728965
217
-22.9068467
-43.1728965
218
-22.9068467
-43.1728965
219
-22.9068467
-43.1728965
220
-22.9068467
-43.1728965
221
-22.9068467
-43.1728965
222
-22.9068467
-43.1728965
223
-34.90111270000001
-56.16453139999999
-34.90111270000001
-56.16453139999999
225
-34.90111270000001
-56.16453139999999
226
-34.90111270000001
-56.16453139999999
227
-34.90111270000001
-56.16453139999999
228
-34.90111270000001
-56.16453139999999
229
-34.90111270000001
-56.16453139999999
230
-34.90111270000001
-56.16453139999999
231
-34.90111270000001
-56.16453139999999
232
-34.90111270000001
-56.16453139999999
233
-34.90111270000001
-56.16453139999999
234
-34.90111270000001
-56.16453139999999
235
-34.90111270000001
-56.16453139999999
236
-34.90111270000001
-56.16453139999999
237
-34.90111270000001
-56.16453139999999
238
-34.90111270000001
-56.16453139999999
239
-34.6036844
-58.3815591
-34.6036844
-58.3815591
241
-34.6036844
-58.3815591
242
-34.6036844
-58.3815591
243
-34.6036844
-58.3815591
244
-34.6036844
-58.3815591
245
-34.6036844
-58.3815591
246
-34.6036844
-58.3815591
247
-34.6036844
-58.3815591
248
-34.6036844
-58.3815591
249
-34.6036844
-58.3815591
250
-34.6036844
-58.3815591
251
-34.6036844
-58.3815591
252
-34.6036844
-58.3815591
253
-34.6036844
-58.3815591
254
-34.6036844
-58.3815591
255
-34.6036844
-58.3815591
256
-34.6036844
-58.3815591
257
-34.6036844
-58.3815591
258
-34.6036844
-58.3815591
259
-34.6036844
-58.3815591
260
-34.6036844
-58.3815591
261
-34.6036844
-58.3815591
262
-34.6036844
-58.3815591
263
-34.6036844
-58.3815591
264
-34.6036844
-58.3815591
265
-34.6036844
-58.3815591
266
-34.6036844
-58.3815591
267
-34.6036844
-58.3815591
268
-34.6036844
-58.3815591
269
-34.6036844
-58.3815591
270
-34.6036844
-58.3815591
271
-34.6036844
-58.3815591
272
-34.6036844
-58.3815591
273
-34.6036844
-58.3815591
274
-34.6036844
-58.3815591
275
-34.6036844
-58.3815591
276
-34.6036844
-58.3815591
277
-34.6036844
-58.3815591
278
-34.6036844
-58.3815591
279
-34.6036844
-58.3815591
280
-34.6036844
-58.3815591
281
-34.6036844
-58.3815591
282
-34.6036844
-58.3815591
283
-34.6036844
-58.3815591
284
-34.6036844
-58.3815591
285
-34.6036844
-58.3815591
286
-34.6036844
-58.3815591
287
-34.6036844
-58.3815591
288
-34.6036844
-58.3815591
289
-34.6036844
-58.3815591
290
-34.6036844
-58.3815591
291
-34.6036844
-58.3815591
292
-34.6036844
-58.3815591
293
-34.6036844
-58.3815591
294
-34.6036844
-58.3815591
295
-34.6036844
-58.3815591
296
-34.6036844
-58.3815591
297
-34.6036844
-58.3815591
298
-34.6036844
-58.3815591
299
-34.6036844
-58.3815591
300
-34.6036844
-58.3815591
301
-34.6036844
-58.3815591
302
-34.6036844
-58.3815591
303
-34.6036844
-58.3815591
304
-34.6036844
-58.3815591
305
-34.6036844
-58.3815591
306
-34.6036844
-58.3815591
307
-34.6036844
-58.3815591
308
-34.6036844
-58.3815591
309
-34.6036844
-58.3815591
310
-34.6036844
-58.3815591
311
-34.6036844
-58.3815591
312
-34.6036844
-58.3815591
313
-34.6036844
-58.3815591
314
-33.4488897
-70.66926550000002
-33.4488897
-70.66926550000002
316
-33.4488897
-70.66926550000002
317
-33.4488897
-70.66926550000002
318
-33.4488897
-70.66926550000002
319
-33.4488897
-70.66926550000002
320
-33.4488897
-70.66926550000002
321
-33.4488897
-70.66926550000002
322
-33.4488897
-70.66926550000002
323
-33.4488897
-70.66926550000002
324
-33.4488897
-70.66926550000002
325
-33.4488897
-70.66926550000002
326
-33.4488897
-70.66926550000002
327
-33.4488897
-70.66926550000002
328
-33.4488897
-70.66926550000002
329
-33.4488897
-70.66926550000002
330
-33.4488897
-70.66926550000002
331
-33.4488897
-70.66926550000002
332
-34.6036844
-58.3815591
-38.0054771
-57.5426106
-38.0054771
-57.5426106
335
-38.0054771
-57.5426106
336
-38.0054771
-57.5426106
337
-38.0054771
-57.5426106
338
-38.0054771
-57.5426106
339
-38.0054771
-57.5426106
340
-38.0054771
-57.5426106
341
-38.0054771
-57.5426106
342
-38.0054771
-57.5426106
343
-38.0054771
-57.5426106
344
-38.0054771
-57.5426106
345
-38.0054771
-57.5426106
346
-38.0054771
-57.5426106
347
-38.0054771
-57.5426106
348
-38.0054771
-57.5426106
349
-38.0054771
-57.5426106
350
-38.0054771
-57.5426106
351
-38.0054771
-57.5426106
352
-38.0054771
-57.5426106
353
-38.0054771
-57.5426106
354
-38.0054771
-57.5426106
355
-34.6036844
-58.3815591
-34.6036844
-58.3815591
357
-12.0463731
-77.042754
-12.0463731
-77.042754
359
-12.0463731
-77.042754
360
-12.0463731
-77.042754
361
-12.0463731
-77.042754
362
-12.0463731
-77.042754
363
-12.0463731
-77.042754
364
-12.0463731
-77.042754
365
-12.0463731
-77.042754
366
-12.0463731
-77.042754
367
-12.0463731
-77.042754
368
-12.0463731
-77.042754
369
-12.0463731
-77.042754
370
-12.0463731
-77.042754
371
-12.0463731
-77.042754
372
-12.0463731
-77.042754
373
-12.0463731
-77.042754
374
-12.0463731
-77.042754
375
-12.0463731
-77.042754
376
-12.0463731
-77.042754
377
-12.0463731
-77.042754
378
-12.0463731
-77.042754
379
-12.0463731
-77.042754
380
-12.0463731
-77.042754
381
-0.1806532
-78.4678382
-0.1806532
-78.4678382
383
-0.1806532
-78.4678382
384
-0.1806532
-78.4678382
385
3.4516467000000004
-76.53198540000002
3.4516467000000004
-76.53198540000002
387
4.710988599999999
-74.072092
4.710988599999999
-74.072092
389
4.710988599999999
-74.072092
390
4.710988599999999
-74.072092
391
4.710988599999999
-74.072092
392
4.710988599999999
-74.072092
393
4.710988599999999
-74.072092
394
4.710988599999999
-74.072092
395
4.710988599999999
-74.072092
396
4.710988599999999
-74.072092
397
4.710988599999999
-74.072092
398
4.710988599999999
-74.072092
399
4.710988599999999
-74.072092
400
4.710988599999999
-74.072092
401
4.710988599999999
-74.072092
402
6.244203
-75.5812119
6.244203
-75.5812119
404
11.004107199999998
-74.80698129999998
11.004107199999998
-74.80698129999998
406
11.004107199999998
-74.80698129999998
407
10.3910485
-75.4794257
11.004107199999998
-74.80698129999998
11.004107199999998
-74.80698129999998
410
11.004107199999998
-74.80698129999998
411
10.480593699999998
-66.90360629999999
10.480593699999998
-66.90360629999999
413
10.480593699999998
-66.90360629999999
414
10.480593699999998
-66.90360629999999
415
10.480593699999998
-66.90360629999999
416
10.480593699999998
-66.90360629999999
417
10.480593699999998
-66.90360629999999
418
10.480593699999998
-66.90360629999999
419
10.480593699999998
-66.90360629999999
420
10.480593699999998
-66.90360629999999
421
10.480593699999998
-66.90360629999999
422
10.480593699999998
-66.90360629999999
423
18.017874300000006
-76.8099041
18.017874300000006
-76.8099041
425
18.5138139
-72.2881907
18.5138139
-72.2881907
427
18.5138139
-72.2881907
428
18.5138139
-72.2881907
429
18.5138139
-72.2881907
430
18.017874300000006
-76.8099041
18.017874300000006
-76.8099041
432
18.017874300000006
-76.8099041
433
18.017874300000006
-76.8099041
434
18.017874300000006
-76.8099041
435
18.017874300000006
-76.8099041
436
18.017874300000006
-76.8099041
437
18.017874300000006
-76.8099041
438
18.017874300000006
-76.8099041
439
18.017874300000006
-76.8099041
440
18.017874300000006
-76.8099041
441
18.017874300000006
-76.8099041
442
18.017874300000006
-76.8099041
443
18.017874300000006
-76.8099041
444
18.017874300000006
-76.8099041
445
18.017874300000006
-76.8099041
446
18.017874300000006
-76.8099041
447
18.017874300000006
-76.8099041
448
18.017874300000006
-76.8099041
449
18.017874300000006
-76.8099041
450
18.017874300000006
-76.8099041
451
18.017874300000006
-76.8099041
452
18.017874300000006
-76.8099041
453
18.017874300000006
-76.8099041
454
18.017874300000006
-76.8099041
455
18.017874300000006
-76.8099041
456
18.017874300000006
-76.8099041
457
18.594395
-72.30743259999998
18.594395
-72.30743259999998
459
18.594395
-72.30743259999998
460
18.594395
-72.30743259999998
461
18.594395
-72.30743259999998
462
18.594395
-72.30743259999998
463
18.594395
-72.30743259999998
464
18.594395
-72.30743259999998
465
18.594395
-72.30743259999998
466
18.594395
-72.30743259999998
467
18.594395
-72.30743259999998
468
18.594395
-72.30743259999998
469
18.594395
-72.30743259999998
470
18.594395
-72.30743259999998
471
18.594395
-72.30743259999998
472
18.594395
-72.30743259999998
473
18.594395
-72.30743259999998
474
18.594395
-72.30743259999998
475
18.594395
-72.30743259999998
476
18.594395
-72.30743259999998
477
18.594395
-72.30743259999998
478
18.594395
-72.30743259999998
479
18.594395
-72.30743259999998
480
18.594395
-72.30743259999998
481
18.594395
-72.30743259999998
482
18.594395
-72.30743259999998
483
18.594395
-72.30743259999998
484
18.594395
-72.30743259999998
485
18.594395
-72.30743259999998
486
18.594395
-72.30743259999998
487
18.594395
-72.30743259999998
488
18.594395
-72.30743259999998
489
18.594395
-72.30743259999998
490
18.594395
-72.30743259999998
491
18.594395
-72.30743259999998
492
18.594395
-72.30743259999998
493
18.594395
-72.30743259999998
494
18.594395
-72.30743259999998
495
18.594395
-72.30743259999998
496
18.594395
-72.30743259999998
497
18.594395
-72.30743259999998
498
18.594395
-72.30743259999998
499
18.594395
-72.30743259999998
500
18.594395
-72.30743259999998
501
18.594395
-72.30743259999998
502
18.594395
-72.30743259999998
503
18.594395
-72.30743259999998
504
18.594395
-72.30743259999998
505
18.594395
-72.30743259999998
506
18.594395
-72.30743259999998
507
18.594395
-72.30743259999998
508
18.594395
-72.30743259999998
509
18.594395
-72.30743259999998
510
18.594395
-72.30743259999998
511
18.594395
-72.30743259999998
512
18.594395
-72.30743259999998
513
18.594395
-72.30743259999998
514
18.594395
-72.30743259999998
515
18.594395
-72.30743259999998
516
18.594395
-72.30743259999998
517
18.594395
-72.30743259999998
518
18.594395
-72.30743259999998
519
18.594395
-72.30743259999998
520
18.594395
-72.30743259999998
521
18.594395
-72.30743259999998
522
18.594395
-72.30743259999998
523
18.594395
-72.30743259999998
524
18.594395
-72.30743259999998
525
18.594395
-72.30743259999998
526
18.594395
-72.30743259999998
527
18.594395
-72.30743259999998
528
18.594395000000002
-72.30743259999998
529
18.594395
-72.30743259999998
530
18.594395
-72.30743259999998
531
18.594395
-72.30743259999998
532
18.594395
-72.30743259999998
533
18.594395
-72.30743259999998
534
18.594395
-72.30743259999998
535
18.594395
-72.30743259999998
536
18.594395
-72.30743259999998
537
18.594395
-72.30743259999998
538
18.594395
-72.30743259999998
539
18.594395
-72.30743259999998
18.594395
-72.30743259999998
541
18.594395
-72.30743259999998
542
18.594395
-72.30743259999998
543
18.594395
-72.30743259999998
544
18.594395
-72.30743259999998
545
18.594395
-72.30743259999998
546
18.594395
-72.30743259999998
547
18.594395
-72.30743259999998
548
18.594395
-72.30743259999998
549
18.594395
-72.30743259999998
550
18.594395
-72.30743259999998
551
18.594395
-72.30743259999998
552
18.594395
-72.30743259999998
553
18.594395
-72.30743259999998
554
18.594395
-72.30743259999998
555
18.594395
-72.30743259999998
556
18.594395
-72.30743259999998
557
18.594395
-72.30743259999998
558
18.594395
-72.30743259999998
559
18.594395
-72.30743259999998
560
18.594395
-72.30743259999998
561
18.594395000000002
-72.30743259999998
562
19.4326077
-99.133208
20.6596988
-103.3496092
20.6596988
-103.3496092
565
20.6596988
-103.3496092
566
20.6596988
-103.3496092
567
20.6596988
-103.3496092
568
20.6596988
-103.3496092
569
20.6596988
-103.3496092
570
20.6596988
-103.3496092
571
20.6596988
-103.3496092
572
20.6596988
-103.3496092
573
20.6596988
-103.3496092
574
19.4326077
-99.133208
36.1699412
-115.13982959999998
36.1699412
-115.13982959999998
577
36.1699412
-115.13982959999998
578
36.1699412
-115.13982959999998
579
36.1699412
-115.13982959999998
580
36.1699412
-115.13982959999998
581
36.1699412
-115.13982959999998
582
36.1699412
-115.13982959999998
583
36.1699412
-115.13982959999998
584
36.1699412
-115.13982959999998
585
36.1699412
-115.13982959999998
586
36.1699412
-115.13982959999998
587
36.1699412
-115.13982959999998
588
36.1699412
-115.13982959999998
589
36.1699412
-115.13982959999998
590
36.1699412
-115.13982959999998
591
36.1699412
-115.13982959999998
592
36.1699412
-115.13982959999998
593
39.5296329
-119.8138027
39.5296329
-119.8138027
595
39.5296329
-119.8138027
596
39.5296329
-119.8138027
597
39.5296329
-119.8138027
598
39.5296329
-119.8138027
599
39.5296329
-119.8138027
600
39.5296329
-119.8138027
601
39.5296329
-119.8138027
602
34.0928092
-118.3286614
34.0928092
-118.3286614
604
34.0928092
-118.3286614
605
34.0928092
-118.3286614
606
34.0928092
-118.3286614
607
34.0928092
-118.3286614
608
34.0928092
-118.3286614
609
34.0928092
-118.3286614
610
34.0928092
-118.3286614
611
34.0928092
-118.3286614
612
34.0928092
-118.3286614
613
40.7127753
-74.0059728
40.7127753
-74.0059728
615
40.7127753
-74.0059728
616
40.7127753
-74.0059728
617
48.954408
-54.6103488
48.856614
2.3522218999999995
48.856614
2.3522218999999995
620
48.856614
2.3522218999999995
621
48.856614
2.3522218999999995
622
48.856614
2.3522218999999995
623
48.856614
2.3522218999999995
624
48.856614
2.3522218999999995
625
48.856614
2.3522218999999995
626
48.856614
2.3522218999999995
627
48.856614
2.3522218999999995
628
48.856614
2.3522218999999995
629
48.856614
2.3522218999999995
630
48.856614
2.3522218999999995
631
48.856614
2.3522218999999995
632
48.856614
2.3522218999999995
633
48.856614
2.3522218999999995
634
48.856614
2.3522218999999995
635
48.856614
2.3522218999999995
636
48.856614
2.3522218999999995
637
48.856614
2.3522218999999995
638
48.856614
2.3522218999999995
639
48.856614
2.3522218999999995
640
48.856614
2.3522218999999995
641
48.856614
2.3522218999999995
642
48.856614
2.3522218999999995
643
48.856614
2.3522218999999995
644
48.856614
2.3522218999999995
645
48.856614
2.3522218999999995
646
48.856614
2.3522218999999995
647
48.856614
2.3522218999999995
648
48.856614
2.3522218999999995
649
48.856614
2.3522218999999995
650
48.856614
2.3522218999999995
651
48.856614
2.3522218999999995
652
48.856614
2.3522218999999995
653
48.856614

709
51.5073509
-0.12775830000000002
710
51.5073509
-0.12775830000000002
711
51.5073509
-0.12775830000000002
712
51.5073509
-0.12775830000000002
713
51.5073509
-0.12775830000000002
714
51.5073509
-0.12775830000000002
715
51.5073509
-0.12775830000000002
716
51.5073509
-0.12775830000000002
717
51.5073509
-0.12775830000000002
718
51.5073509
-0.12775830000000002
719
51.5073509
-0.12775830000000002
720
51.5073509
-0.12775830000000002
721
51.5073509
-0.12775830000000002
722
51.5073509
-0.12775830000000002
723
51.5073509
-0.12775830000000002
724
51.5073509
-0.12775830000000002
725
51.5073509
-0.12775830000000002
726
51.5073509
-0.12775830000000002
727
51.5073509
-0.12775830000000002
728
51.5073509
-0.12775830000000002
729
51.5073509
-0.12775830000000002
730
51.5073509
-0.12775830000000002
731
51.5073509
-0.12775830000000002
732
51.5073509
-0.12775830000000002
733
51.5073509
-0.12775830000000002
734
51.5073509
-0.12775830000000002
735
51.5073509
-0.12775830000000002
736
51.5073509
-0.12775830000000002
737
51.5073509
-0.12775830000000002
738
51.5073509
-0.12775830000000002
739
51.5073509
-0.12775830000000002
740
51.5073509
-0.12775830000000002
741
51.5073509
-0.12775830000000002
742
51.5073509
-0.12775830000000002
743
51.5073509
-0.12775830000000002
744
51.5073509
-0.12775830000000002
745
51.5073509
-0.12775830000000002
746
51.5073509
-0.12775830000000002
747
51.5073509
-0.12775830000000002
748
51.5073509
-0.12775830000000002
749
51.5073509
-0.12775830000000002
750
51.5073509
-0.12775830000000002
751
51.5073509
-0.12775830000000002
752
51.5073509
-0.12775830000000002
753
51.5073509
-0.12775830000000002
754
51.5073509
-0.12775830000000002
755
51.5073509
-0.12775830000000002
756
51.5073509
-0.12775830000000002
757
51.5073509
-0.12775830000000002
758
51.5073509
-0.12775830000000002
759
51.5073509
-0.12775830000000002
760
51.5073509
-0.12775830000000002
761
51.5073509
-0.12775830000000002
762
51.5073509
-0.12775830000000002
763
51.5073509
-0.12775830000000002
764
51.5073509
-0.12775830000000002
765
51.5073509
-0.12775830000000002
766
51.5073509
-0.12775830000000002
767
51.5073509
-0.12775830000000002
768
51.5073509
-0.12775830000000002
769
51.5073509
-0.12775830000000002
770
51.5073509
-0.12775830000000002
771
51.5073509
-0.12775830000000002
772
51.5073509
-0.12775830000000002
773
51.5073509
-0.12775830000000002
774
51.5073509
-0.12775830000000002
775
51.5073509
-0.12775830000000002
776
51.5073509
-0.12775830000000002
777
51.5073509
-0.12775830000000002
778
51.5073509
-0.12775830000000002
779
51.5073509
-0.12775830000000002
780
51.5073509
-0.12775830000000002
781
51.5073509
-0.12775830000000002
782
51.5073509
-0.12775830000000002
783
51.5073509
-0.12775830000000002
784
51.5073509
-0.12775830000000002
785
51.5073509
-0.12775830000000002
786
51.5073509
-0.12775830000000002
787
51.5073509
-0.12775830000000002
788
51.5073509
-0.12775830000000002
789
51.5073509
-0.12775830000000002
790
51.5073509
-0.12775830000000002
791
51.5073509
-0.12775830000000002
792
51.5073509
-0.12775830000000002
793
51.5073509
-0.12775830000000002
794
51.5073509
-0.12775830000000002
795
51.5073509
-0.12775830000000002
796
51.5073509
-0.12775830000000002
797
51.5073509
-0.12775830000000002
798
51.5073509
-0.12775830000000002
799
51.5073509
-0.12775830000000002
800
51.5073509
-0.12775830000000002
801
51.5073509
-0.12775830000000002
802
51.5073509
-0.12775830000000002
803
51.5073509
-0.12775830000000002
804
51.5073509
-0.12775830000000002
805
51.5073509
-0.12775830000000002
806
51.5073509
-0.12775830000000002
807
51.5073509
-0.12775830000000002
808
51.5073509
-0.12775830000000002
809
51.5073509
-0.12775830000000002
810
51.5073509
-0.12775830000000002
811
51.5073509
-0.12775830000000002
812
51.5073509
-0.12775830000000002
813
51.5073509
-0.12775830000000002
814
54.97647900000001
-5.0268868
54.59728500000001
-5.93012
54.59728500000001
-5.93012
817
54.59728500000001
-5.93012
818
54.59728500000001
-5.93012
819
54.59728500000001
-5.93012
820
54.59728500000001
-5.93012
821
54.59728500000001
-5.93012
822
54.59728500000001
-5.93012
823
54.59728500000001
-5.93012
824
54.59728500000001
-5.93012
825
54.59728500000001
-5.93012
826
54.59728500000001
-5.93012
827
54.59728500000001
-5.93012
828
53.34980529999999
-6.2603097000000005
53.34980529999999
-6.2603097000000005
830
53.34980529999999
-6.2603097000000005
831
53.34980529999999
-6.2603097000000005
832
53.34980529999999
-6.2603097000000005
833
53.34980529999999
-6.2603097000000005
834
53.34980529999999
-6.2603097000000005
835
51.5073509
-0.12775830000000002
50.719164
-1.880769
50.719164
-1.880769
838
50.719164
-1.880769
839
50.719164
-1.880769
840
50.719164
-1.880769
841
50.719164
-1.880769
842
50.719164
-1.880769
843
50.719164
-1.880769
844
50.719164
-1.880769
845
50.719164
-1.880769
846
50.719164
-1.880769
847
50.719164
-1.880769
848
50.719164
-1.880769
849
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
851
52.95478319999999
-1.1581086
852
52.95478319999999
-1.1581086
853
52.95478319999999
-1.1581086
854
52.95478319999999
-1.1581086
855
52.95478319999999
-1.1581086
856
52.95478319999999
-1.1581086
857
52.95478319999999
-1.1581086
858
52.95478319999999
-1.1581086
859
52.95478319999999
-1.1581086
860
52.95478319999999
-1.1581086
861
52.95478319999999
-1.1581086
862
52.95478319999999
-1.1581086
863
52.48624299999999
-1.890401
52.48624299999999
-1.890401
865
52.48624299999999
-1.890401
866
52.48624299999999
-1.890401
867
52.48624299999999
-1.890401
868
52.48624299999999
-1.890401
869
52.48624299999999
-1.890401
870
52.48624299999999
-1.890401
871
52.48624299999999
-1.890401
872
52.48624299999999
-1.890401
873
52.48624299999999
-1.890401
874
52.48624299999999
-1.890401
875
52.48624299999999
-1.890401
876
52.48624299999999
-1.890401
877
51.454513
-2.58791
51.454513
-2.58791
879
51.454513
-2.58791
880
51.454513
-2.58791
881
51.454513
-2.58791
882
51.454513
-2.58791
883
51.454513
-2.58791
884
51.454513
-2.58791
885
51.454513
-2.58791
886
51.454513
-2.58791
887
51.454513
-2.58791
888
51.454513
-2.58791
889
51.454513
-2.58791
890
51.454513
-2.58791
891
51.5073509
-0.12775830000000002
51.5073509
-0.12775830000000002
893
51.5073509
-0.12775830000000002
894
55.6760968
12.568337199999998
55.6760968
12.568337199999998
896
55.6760968
12.568337199999998
897
55.6760968
12.568337199999998
898
55.6760968
12.568337199999998
899
55.6760968
12.568337199999998
900
55.6760968
12.568337199999998
901
55.6760968
12.568337199999998
902
55.6760968
12.568337199999998
903
55.6760968
12.568337199999998
904
55.6760968
12.568337199999998
905
55.6760968
12.568337199999998
906
55.6760968
12.568337199999998
907
55.6760968
12.568337199999998
908
55.6760968
12.568337199999998
909
55.6760968
12.568337199999998
910
55.6760968
12.568337199999998
911
55.6760968
12.568337199999998
912
55.6760968
12.568337199999998
913
55.6760968
12.568337199999998
914
55.6760968
12.568337199999998
915
55.6760968
12.568337199999998
916
55.6760968
12.568337199999998
917
55.6760968
12.568337199999998
918
55.6760968
12.568337199999998
919
48.856614
2.3522218999999995
48.856614
2.3522218999999995
921
48.856614
2.3522218999999995
922
48.856614
2.3522218999999995
923
48.856614
2.3522218999999995
924
48.856614
2.3522218999999995
925
48.856614
2.3522218999999995
926
46.13185900000001
3.425488
46.13185900000001
3.425488
928
43.56919050000001
7.112385400000001
43.296482
5.36978
43.7101728
7.2619532000000016
44.652297
-1.1785016
44.652297
-1.1785016
933
43.4831519
-1.558626
43.4831519
-1.558626
935
43.4831519
-1.558626
936
43.4831519
-1.558626
937
43.4831519
-1.558626
938
43.708608
-1.051945
41.3850639
2.1734035
41.3850639
2.1734035
941
41.3850639
2.1734035
942
41.3850639
2.1734035
943
41.3850639
2.1734035
944
41.3850639
2.1734035
945
41.3850639
2.1734035
946
41.3850639
2.1734035
947
41.3850639
2.1734035
948
41.3850639
2.1734035
949
41.3850639
2.1734035
950
41.3850639
2.1734035
951
41.3850639
2.1734035
952
41.3850639
2.1734035
953
41.3850639
2.1734035
954
41.3850639
2.1734035
955
43.79123660000001
7.6075864
45.4642035
9.189982
45.4642035
9.189982
958
45.4642035
9.189982
959
45.4642035
9.189982
960
45.4642035
9.189982
961
45.4642035
9.189982
962
45.4642035
9.189982
963
45.4642035
9.189982
964
45.4642035
9.189982
965
45.4642035
9.189982
966
45.4642035
9.189982
967
45.4642035
9.189982
968
41.90278350000001
12.4963655
41.90278350000001
12.4963655
970
41.90278350000001
12.4963655
971
41.90278350000001
12.4963655
972
41.90278350000001
12.4963655
973
41.90278350000001
12.4963655
974
41.90278350000001
12.4963655
975
38.1156879
13.3612671
38.1156879
13.3612671
977
37.5078772
15.0830304
37.5078772
15.0830304
979
40.85177460000001
14.2681244
40.85177460000001
14.2681244
981
40.85177460000001
14.2681244
982
45.070312
7.6868564999999975
45.070312
7.6868564999999975
984
44.4056499
8.946256
44.4056499
8.946256
986
44.3254364
9.195443199999998
44.3254364
9.195443199999998
988
44.3254364
9.195443199999998
989
44.3254364
9.195443199999998
990
43.296482
5.36978
43.296482
5.36978
992
43.296482
5.36978
993
43.296482
5.36978
994
43.296482
5.36978
995
43.296482
5.36978
996
43.296482
5.36978
997
43.296482
5.36978
998
43.296482
5.36978
999
46.9479739
7.447446799999999
46.9479739
7.447446799999999
1001
46.9479739
7.447446799999999
1002
47.37688660000001
8.541694
47.37688660000001
8.541694
1004
47.37688660000001
8.541694
1005
47.37688660000001
8.541694
1006
47.205557
7.455571000000001
46.5196535
6.6322734
47.5595986
7.5885761
47.5595986
7.5885761
1010
41.90278350000001
12.4963655
41.90278350000001
12.4963655
1012
37.5999938
14.0153557
38.1156879
13.3612671
38.1156879
13.3612671
1015
38.1156879
13.3612671
1016
37.5078772
15.0830304
41.1171432
16.8718715
41.1171432
16.8718715
1019
40.85177460000001
14.2681244
40.85177460000001
14.2681244
1021
40.85177460000001
14.2681244
1022
40.85177460000001
14.2681244
1023
43.548473
10.3105674
43.7695604
11.2558136
43.7695604
11.2558136
1026
45.6495264
13.7768182
45.6495264
13.7768182
1028
45.6495264
13.7768182
1029
45.4064349
11.8767611
45.5415526
10.2118019
45.82059890000001
8.825057600000003
45.82059890000001
8.825057600000003
1033
45.6982642
9.6772698
45.6982642
9.6772698
1035
45.43838419999999
10.9916215
45.43838419999999
10.9916215
1037
44.494887
11.3426162
44.494887
11.3426162
1039
44.494887
11.3426162
1040
41.90278350000001
12.4963655
41.90278350000001
12.4963655
1042
41.90278350000001
12.4963655
1043
41.90278350000001
12.4963655
1044
41.90278350000001
12.4963655
1045
41.90278350000001
12.4963655
1046
48.856614
2.3522218999999995
48.856614
2.3522218999999995
1048
48.856614
2.3522218999999995
1049
48.856614
2.3522218999999995
1050
48.856614
2.3522218999999995
1051
48.856614
2.3522218999999995
1052
48.856614
2.3522218999999995
1053
48.856614
2.3522218999999995
1054
48.856614
2.3522218999999995
1055
48.856614
2.3522218999999995
1056
48.856614
2.3522218999999995
1057
48.856614
2.3522218999999995
1058
48.856614
2.3522218999999995
1059
48.856614
2.3522218999999995
1060
48.856614
2.3522218999999995
1061
48.856614
2.3522218999999995
1062
48.856614
2.3522218999999995
1063
48.856614
2.3522218999999995
1064
48.856614
2.3522218999999995
1065
48.856614
2.3522218999999995
1066
48.856614
2.3522218999999995
1067
48.856614
2.3522218999999995
1068
48.856614
2.3522218999999995
1069
48.856614
2.3522218999999995
1070
48.856614
2.3522218999999995
1071
48.856614
2.3522218999999995
1072
48.856614
2.3522218999999995
1073
48.856614
2.3522218999999995
1074
48.856614
2.3522218999999995
1075
48.856614
2.3522218999999995
1076
48.856614
2.3522218999999995
1077
48.856614
2.3522218999999995
1078
48.856614
2.3522218999999995
1079
48.856614
2.3522218999999995
1080
48.856614
2.3522218999999995
1081
48.856614
2.3522218999999995
1082
48.856614
2.3522218999999995
1083
48.856614
2.3522218999999995
1084
48.856614
2.3522218999999995
1085
44.837789
-0.57918
44.837789
-0.57918
1087
48.856614
2.3522218999999995
48.856614
2.3522218999999995
1089
48.856614
2.3522218999999995
1090
48.856614
2.3522218999999995
1091
48.856614
2.3522218999999995
1092
48.856614
2.3522218999999995
1093
48.856614
2.3522218999999995
1094
48.856614
2.3522218999999995
1095
48.856614
2.3522218999999995
1096
35.69706970000001
-0.6307988
35.69706970000001
-0.6307988
1098
33.5731104
-7.589843399999999
33.5731104
-7.589843399999999
1100
48.856614
2.3522218999999995
48.856614
2.3522218999999995
1102
40.7127753
-74.0059728
40.7127753
-74.0059728
1104
41.8781136
-87.62979820000002
41.525031
-88.0817251
34.0928092
-118.3286614
34.0928092
-118.3286614
1108
34.0928092
-118.3286614
1109
34.0928092
-118.3286614
1110
34.0928092
-118.3286614
1111
34.0928092
-118.3286614
1112
34.0928092
-118.3286614
1113
34.0928092
-118.3286614
1114
34.0928092
-118.3286614
1115
34.0928092
-118.3286614
1116
34.0928092
-118.3286614
1117
34.0928092
-118.3286614
1118
34.0928092
-118.3286614
1119
34.0928092
-118.3286614
1120
34.0928092
-118.3286614
1121
34.0928092
-118.3286614
1122
34.0928092
-118.3286614
1123
34.0928092
-118.3286614
1124
34.0928092
-118.3286614
1125
34.0928092
-118.3286614
1126
34.0928092
-118.3286614
1127
34.0928092
-118.3286614
1128
37.7749295
-122.4194155
37.7749295
-122.4194155
1130
37.7749295
-122.4194155
1131
37.7749295
-122.4194155
1132
37.7749295
-122.4194155
1133
37.7749295
-122.4194155
1134
37.7749295
-122.4194155
1135
37.7749295
-122.4194155
1136
37.7749295
-122.4194155
1137
37.7749295
-122.4194155
1138
37.7749295
-122.4194155
1139
37.7749295
-122.4194155
1140
37.7749295
-122.4194155
1141
37.7749295
-122.4194155
1142
37.7749295
-122.4194155
1143
37.7749295
-122.4194155
1144
37.7749295
-122.4194155
1145
37.7749295
-122.4194155
1146
37.7749295
-122.4194155
1147
37.7749295
-122.4194155
1148
37.7749295
-122.4194155
1149
37.7749295
-122.4194155
1150
37.7749295
-122.4194155
1151
36.1699412
-115.13982959999998
36.1699412
-115.13982959999998
1153
36.1699412
-115.13982959999998
1154
36.1699412
-115.13982959999998
1155

36.1699412
-115.13982959999998
1156
36.1699412
-115.13982959999998
1157
36.1699412
-115.13982959999998
1158
36.1699412
-115.13982959999998
1159
36.1699412
-115.13982959999998
1160
36.1699412
-115.13982959999998
1161
34.0928092
-118.3286614
36.1699412
-115.13982959999998
36.1699412
-115.13982959999998
1164
36.1699412
-115.13982959999998
1165
34.0928092
-118.3286614
34.0928092
-118.3286614
1167
34.0928092
-118.3286614
1168
34.0928092
-118.3286614
1169
34.0928092
-118.3286614
1170
34.0928092
-118.3286614
1171
34.0928092
-118.3286614
1172
34.0928092
-118.3286614
1173
34.0928092
-118.3286614
1174
39.5296329
-119.8138027
39.5296329
-119.8138027
1176
39.5296329
-119.8138027
1177
39.5296329
-119.8138027
1178
39.5296329
-119.8138027
1179
34.0928092
-118.3286614
39.5296329
-119.8138027
39.5296329
-119.8138027
1182
39.5296329
-119.8138027
1183
39.5296329
-119.8138027
1184
39.5296329
-119.8138027
1185
39.5296329
-119.8138027
1186
39.5296329
-119.8138027
1187
39.5296329
-119.8138027
1188
39.5296329
-119.8138027
1189
39.5296329
-119.8138027
1190
34.0928092
-118.3286614
34.0928092
-118.3286614
1192
34.0928092
-118.3286614
1193
34.0928092
-118.3286614
1194
34.0928092
-118.3286614
1195
34.0928092
-118.3286614
1196
34.0928092
-118.3286614
1197
34.0928092
-118.3286614
1198
34.0928092
-118.3286614
1199
34.0928092
-118.3286614
1200
34.0928092
-118.3286614
1201
34.0928092
-118.3286614
1202
34.0928092
-118.3286614
1203
34.0928092
-118.3286614
1204
34.0928092
-118.3286614
1205
34.0928092
-118.3286614
1206
34.0928092
-118.3286614
1207
34.0928092
-118.3286614
1208
34.0928092
-118.3286614
1209
34.0928092
-118.3286614
1210
34.0928092
-118.3286614
1211
34.0928092
-118.3286614
1212
34.0928092
-118.3286614
1213
34.0928092
-118.3286614
1214
34.0928092
-118.3286614
1215
34.0928092
-118.3286614
1216
34.0928092
-118.3286614
1217
34.0928092
-118.3286614
1218
34.0928092
-118.3286614
1219
34.0928092
-118.3286614
1220
49.28272910000001
-123.1207375
49.28272910000001
-123.1207375
1222
49.28272910000001
-123.1207375
1223
49.28272910000001
-123.1207375
1224
49.28272910000001
-123.1207375
1225
49.28272910000001
-123.1207375
1226
49.28272910000001
-123.1207375
1227
49.28272910000001
-123.1207375
1228
49.28272910000001
-123.1207375
1229
49.28272910000001
-123.1207375
1230
49.28272910000001
-123.1207375
1231
49.28272910000001
-123.1207375
1232
49.28272910000001
-123.1207375
1233
49.28272910000001
-123.1207375
1234
49.28272910000001
-123.1207375
1235
39.22782720000001
-120.0047095
39.22782720000001
-120.0047095
1237
39.22782720000001
-120.0047095
1238
39.22782720000001
-120.0047095
1239
39.22782720000001
-120.0047095
1240
39.22782720000001
-120.0047095
1241
39.22782720000001
-120.0047095
1242
39.22782720000001
-120.0047095
1243
39.22782720000001
-120.0047095
1244
39.22782720000001
-120.0047095
1245
34.0928092
-118.3286614
34.0928092
-118.3286614
1247
34.0928092
-118.3286614
1248
34.0928092
-118.3286614
1249
34.0928092
-118.3286614
1250
34.0928092
-118.3286614
1251
34.0928092
-118.3286614
1252
34.0928092
-118.3286614
1253
34.0928092
-118.3286614
1254
34.0928092
-118.3286614
1255
34.0928092
-118.3286614
1256
34.0928092
-118.3286614
1257
34.0928092
-118.3286614
1258
34.0928092
-118.3286614
1259
34.0928092
-118.3286614
1260
34.0928092
-118.3286614
1261
34.0928092
-118.3286614
1262
34.0928092
-118.3286614
1263
34.0928092
-118.3286614
1264
34.0928092
-118.3286614
1265
34.0928092
-118.3286614
1266
34.0928092
-118.3286614
1267
34.0928092
-118.3286614
1268
34.0928092
-118.3286614
1269
34.0928092
-118.3286614
1270
34.0928092
-118.3286614
1271
34.0928092
-118.3286614
1272
34.0928092
-118.3286614
1273
34.0928092
-118.3286614
1274
34.0928092
-118.3286614
1275
34.0928092
-118.3286614
1276
34.0928092
-118.3286614
1277
34.0928092
-118.3286614
1278
34.0928092
-118.3286614
1279
34.0928092
-118.3286614
1280
34.0928092
-118.3286614
1281
34.0928092
-118.3286614
1282
34.0928092
-118.3286614
1283
34.0928092
-118.3286614
1284
23.1135925
-82.36659559999998
23.1135925
-82.36659559999998
1286
23.1135925
-82.36659559999998
1287
34.0522342
-118.24368490000002
34.0522342
-118.24368490000002
1289
34.0522342
-118.24368490000002
1290
34.0522342
-118.24368490000002
1291
34.0522342
-118.24368490000002
1292
34.0522342
-118.24368490000002
1293
34.0522342
-118.24368490000002
1294
34.0522342
-118.24368490000002
1295
34.0522342
-118.24368490000002
1296
34.0522342
-118.24368490000002
1297
37.7749295
-122.4194155
37.7749295
-122.4194155
1299
37.7749295
-122.4194155
1300
37.7749295
-122.4194155
34.0736204
-118.4003563
40.7127753
-74.0059728
48.856614
2.3522218999999995
41.90278350000001
12.4963655
41.90278350000001
12.4963655
1306
41.90278350000001
12.4963655
1307
41.90278350000001
12.4963655
1308
41.90278350000001
12.4963655
1309
41.90278350000001
12.4963655
1310
41.90278350000001
12.4963655
1311
41.90278350000001
12.4963655
1312
41.90278350000001
12.4963655
1313
41.90278350000001
12.4963655
1314
41.90278350000001
12.4963655
1315
41.90278350000001
12.4963655
1316
41.90278350000001
12.4963655
1317
41.90278350000001
12.4963655
1318
41.90278350000001
12.4963655
1319
41.90278350000001
12.4963655
1320
41.90278350000001
12.4963655
1321
41.90278350000001
12.4963655
1322
41.90278350000001
12.4963655
1323
41.90278350000001
12.4963655
1324
41.90278350000001
12.4963655
1325
41.90278350000001
12.4963655
1326
41.90278350000001
12.4963655
1327
41.90278350000001
12.4963655
1328
41.90278350000001
12.4963655
1329
41.90278350000001
12.4963655
1330
41.90278350000001
12.4963655
1331
41.90278350000001
12.4963655
1332
41.90278350000001
12.4963655
1333
41.90278350000001
12.4963655
1334
41.90278350000001
12.4963655
1335
41.90278350000001
12.4963655
1336
41.90278350000001
12.4963655
1337
41.90278350000001
12.4963655
1338
41.90278350000001
12.4963655
1339
41.90278350000001
12.4963655
1340
41.90278350000001
12.4963655
1341
41.90278350000001
12.4963655
1342
41.90278350000001
12.4963655
1343

In [163]:
df

,index,Unnamed: 0,Unnamed: 0.1,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same,location
0,0,0,0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
1,1,1,1,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,NaN
2,2,2,2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.856614,2.352222,True,NaN
3,3,3,3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.856614,2.352222,True,NaN
4,4,4,4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,48.856614,2.352222,True,"Paris,France"
5,5,5,5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,48.856614,2.352222,True,NaN
6,6,6,6,1950-01-07,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,"Paris,France"
7,7,7,7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
8,8,8,8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
9,9,9,9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
10,10,10,10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
11,11,11,11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
12,12,12,12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
13,13,13,13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
14,14,14,14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
15,15,15,15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
16,16,16,16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
17,17,17,17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
18,18,18,18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
19,19,19,19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
20,20,20,20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
21,21,21,21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
22,22,22,22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
23,23,23,23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
24,24,24,24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
25,25,25,25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
26,26,26,26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7",48.856614,2.352222,True,NaN
27,27,27,27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
28,28,28,28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,NaN
29,29,29,29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,48.856614,2.352222,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,1431,1431,1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1315,1432,1432,1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1316,1433,1433,1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1317,1434,1434,1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1318,1435,1435,1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1319,1436,1436,1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1320,1437,1437,1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1321,1438,1438,1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1322,1439,1439,1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,41.902784,12.496365,True,NaN
1323,1440,1440,1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1324,1441,1441,1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1325,1442,1442,1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1326,1443,1443,1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,NaN
1327,1444,1444,1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1328,1445,1445,1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1329,1446,1446,1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1330,1447,1447,1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.902784,12.496365,True,NaN
1331,1448,1448,1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1332,1449,1449,1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1333,1450,1450,1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1334,1451,1451,1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1335,1452,1452,1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1336,1453,1453,1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1337,1454,1454,1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1338,1455,1455,1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1339,1456,1456,1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1340,1457,1457,1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1341,1458,1458,1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1342,1459,1459,1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN
1343,1460,1460,1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN,41.902784,12.496365,True,NaN

                  0   1           2           3          4           5
0             Paris  30  1950-01-01  1950-01-30  48.856614    2.352222
1             Cairo   4  1950-02-01  1950-02-04  30.044420   31.235712
2              Rome   1  1950-02-06  1950-02-05  41.902784   12.496365
3             Turin   1  1950-02-07  1950-02-07  45.070312    7.686856
4             Genoa   1  1950-02-09  1950-02-09  44.405650    8.946256
5               NaN   1  1950-02-11  1950-02-10  36.054574  -95.923037
6            Naples   1  1950-02-12  1950-02-12  40.851775   14.268124
7              Rome   8  1950-02-14  1950-02-21  41.902784   12.496365
8               NaN   1  1950-02-23  1950-02-22  36.054574  -95.923037
9          Florence   3  1950-02-24  1950-02-26  43.769560   11.255814
10          Bologna   1  1950-02-28  1950-02-28  44.494887   11.342616
11            Milan  19  1950-03-02  1950-03-20  45.464203    9.189982
12           Venice   2  1950-03-22  1950-03-23  45.440847   12.315515
13            Milan   1  1950-03-25  1950-03-24  45.464203    9.189982
14         Piacenza   1  1950-03-26  1950-03-25  45.052621    9.692984
15          Brescia   1  1950-03-27  1950-03-26  45.541553   10.211802
16           Biella   1  1950-03-28  1950-03-27  45.562884    8.058340
17            Genoa   1  1950-03-29  1950-03-28  44.405650    8.946256
18            Milan   1  1950-03-30  1950-03-29  45.464203    9.189982
19            Paris  11  1950-03-31  1950-04-10  48.856614    2.352222
20    New York City  55  1950-04-12  1950-06-05  40.712775  -74.005973
21            Belem   1  1950-06-07  1950-06-07  -1.455729  -48.490178
22           Recife   5  1950-06-09  1950-06-13  -8.052240  -34.928610
23   Rio de Janeiro  26  1950-06-15  1950-07-10 -22.906847  -43.172897
24        Sao Paulo  18  1950-07-12  1950-07-29 -23.550520  -46.633309
25   Rio de Janeiro  15  1950-07-31  1950-08-14 -22.906847  -43.172897
26       Montevideo  15  1950-08-16  1950-08-30 -34.901113  -56.164531
27     Buenos Aires  74  1950-09-01  1950-11-13 -34.603684  -58.381559
28              NaN   1  1950-11-15  1950-11-14  35.210979 -101.866760
29              NaN   1  1950-11-16  1950-11-15  35.210979 -101.866760
..              ...  ..         ...         ...        ...         ...
221     Los Angeles   9  1953-10-14  1953-10-22  34.052234 -118.243685
222             NaN   1  1953-10-24  1953-10-23  35.210979 -101.866760
223             NaN   1  1953-10-25  1953-10-24  35.210979 -101.866760
224             NaN   1  1953-10-26  1953-10-25  35.210979 -101.866760
225             NaN   1  1953-10-27  1953-10-26  35.210979 -101.866760
226             NaN   1  1953-10-28  1953-10-27  35.210979 -101.866760
227             NaN   1  1953-10-29  1953-10-28  35.210979 -101.866760
228             NaN   1  1953-10-30  1953-10-29  35.210979 -101.866760
229             NaN   1  1953-10-31  1953-10-30  35.210979 -101.866760
230             NaN   1  1953-11-01  1953-10-31  35.210979 -101.866760
231   San Francisco   2  1953-11-02  1953-11-03  37.774929 -122.419415
232  San Francisco    1  1953-11-05  1953-11-04  37.774929 -122.419415
233             NaN   1  1953-11-06  1953-11-05  35.210979 -101.866760
234             NaN   1  1953-11-07  1953-11-06  35.210979 -101.866760
235             NaN   1  1953-11-08  1953-11-07  35.210979 -101.866760
236             NaN   1  1953-11-09  1953-11-08  35.210979 -101.866760
237             NaN   1  1953-11-10  1953-11-09  35.210979 -101.866760
238   Beverly Hills   1  1953-11-11  1953-11-10  34.073620 -118.400356
239             NaN   1  1953-11-12  1953-11-11  35.210979 -101.866760
240             NaN   1  1953-11-13  1953-11-12  35.210979 -101.866760
241             NaN   1  1953-11-14  1953-11-13  35.210979 -101.866760
242             NaN   1  1953-11-15  1953-11-14  35.210979 -101.866760
243             NaN   1  1953-11-16  1953-11-15  35.210979 -101.866760
244             NaN   1  1953-11-17  1953-11-16  35.210979 -101.866760
245             NaN   1  1953-11-18  1953-11-17  35.210979 -101.866760
246             NaN   1  1953-11-19  1953-11-18  35.210979 -101.866760
247        New York   1  1953-11-20  1953-11-19  40.712775  -74.005973
248           Paris   1  1953-11-21  1953-11-20  48.856614    2.352222
249             NaN   1  1953-11-22  1953-11-21  35.210979 -101.866760
250             NaN   1  1953-11-23  1953-11-22  35.210979 -101.866760

[251 rows x 6 columns]

In [164]:
durations_df = pd.DataFrame.from_records(durations, columns=['city_1', 'duration_days', 'min_date', 'max_date', 'lat', 'lng'] )
visits_df = pd.DataFrame.from_records(visits, columns=['city_1', 'visits'])
durations_df.to_csv('durations.csv')
visits_df.to_csv('visits.csv')

In [42]:
df_duration_merge = pd.merge(df, durations_df, left_on = 'city_1', right_on = 'city_1')

In [ ]:
df_duration_returns_merge = pd.merge(df_duration_merge, returns_df, left_on = 'city_1', right_on = 'city_1')

In [171]:
visits_df['city_1'][10:]

10                      Turin
11                   Florence
12                    Bologna
13                    Brescia
14              New York City
15             Rio de Janeiro
16               Barranquilla
17                   Kingston
18                Mexico City
19                   New York
20                    Palermo
21                    Catania
22              San Francisco
23                      Cairo
24                     Venice
25                   Piacenza
26                     Biella
27                      Belem
28                     Recife
29                  Sao Paulo
30                 Montevideo
31                   Santiago
32              Mar del Plata
33                       Lima
34                      Quito
35                       Cali
36                     Bogota
37                   Medellin
38                  Cartagena
39                    Caracas
               ...
58                   Biarritz
59                        Dax
60                  Barcelona
61                Ventimiglia
62    Santa Margherita, Genoa
63                  Marseille
64                       Bern
65                     Zurich
66                     Altreu
67                   Lausanne
68                      Basel
69                     Sicily
70                       Bari
71                    Livorno
72                    Trieste
73                     Padova
74                     Varese
75                    Bergamo
76                     Verona
77                   Bordeaux
78                       Oran
79                 Casablanca
80                    Chicago
81                     Joliet
82                  Vancouver
83            Crystal Bay, NV
84                     Havana
85                Los Angeles
86             San Francisco
87              Beverly Hills
Name: city_1, Length: 78, dtype: object

In [81]:
pd.merge(df, visits_df, left_on = 'city_1', right_on = 'city_1', how='right')

,Unnamed: 0,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same,visits
0,0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
1,1,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,8
2,2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.856614,2.352222,True,8
3,3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.856614,2.352222,True,8
4,4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,48.856614,2.352222,True,8
5,5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,48.856614,2.352222,True,8
6,6,1950-01-07,Paris,France,NaN,NaN,y,NaN,48.856614,2.352222,True,8
7,7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
8,8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
9,9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
10,10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
11,11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
12,12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
13,13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
14,14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
15,15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
16,16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
17,17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
18,18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
19,19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
20,20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
21,21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
22,22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
23,23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
24,24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
25,25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
26,26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7",48.856614,2.352222,True,8
27,27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
28,28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.856614,2.352222,True,8
29,29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,48.856614,2.352222,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1319,1953-08-12,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.282729,-123.120738,True,1
1432,1320,1953-08-13,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.282729,-123.120738,True,1
1433,1321,1953-08-14,Vancouver,Canada,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; SIU ...,49.282729,-123.120738,True,1
1434,1322,1953-08-15,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.282729,-123.120738,True,1
1435,1323,1953-08-16,Vancouver,Canada,NaN,NaN,NaN,NaN,49.282729,-123.120738,True,1
1436,1325,1953-08-18,"Crystal Bay, NV",USA,NaN,NaN,n,NaN,39.227827,-120.004710,False,1
1437,1326,1953-08-19,"Crystal Bay, NV",USA,NaN,NaN,y,NaN,39.227827,-120.004710,True,1
1438,1327,1953-08-20,"Crystal Bay, NV",USA,NaN,NaN,y,NaN,39.227827,-120.004710,True,1
1439,1328,1953-08-21,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.227827,-120.004710,True,1
1440,1329,1953-08-22,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.227827,-120.004710,True,1
1441,1330,1953-08-23,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.227827,-120.004710,True,1
1442,1331,1953-08-24,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.227827,-120.004710,True,1
1443,1332,1953-08-25,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.227827,-120.004710,True,1
1444,1333,1953-08-26,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.227827,-120.004710,True,1
1445,1334,1953-08-27,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.227827,-120.004710,True,1
1446,1376,1953-10-08,Havana,Cuba,NaN,NaN,n,NaN,23.113592,-82.366596,False,1
1447,1377,1953-10-09,Havana,Cuba,NaN,NaN,n,"FBI file; letter to Dale dated Oct 10, 1953 in...",23.113592,-82.366596,True,1
1448,1378,1953-10-10,Havana,Cuba,NaN,NaN,n,"letter to Dale dated Oct 10, 1953 in SIU Box 1...",23.113592,-82.366596,True,1
1449,1381,1953-10-13,Los Angeles,USA,NaN,NaN,y,"MHS Box 22, Personal Log",34.052234,-118.243685,False,1
1450,1382,1953-10-14,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1451,1383,1953-10-15,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1452,1384,1953-10-16,Los Angeles,USA,NaN,NaN,y,SIU Box 16 folder 8,34.052234,-118.243685,True,1
1453,1385,1953-10-17,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1454,1386,1953-10-18,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1455,1387,1953-10-19,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1456,1388,1953-10-20,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1457,1389,1953-10-21,Los Angeles,USA,NaN,NaN,y,SIU Box 16 folder 8,34.052234,-118.243685,True,1
1458,1390,1953-10-22,Los Angeles,USA,NaN,NaN,y,NaN,34.052234,-118.243685,True,1
1459,1403,1953-11-04,San Francisco,USA,NaN,NaN,NaN,NaN,37.774929,-122.419415,False,1
1460,1409,1953-11-10,Beverly Hills,USA,NaN,NaN,n,SIU Box 16 folder 9,34.073620,-118.400356,False,1

In [175]:
test = pd.merge(visits_df,df[['city_1', 'lat', 'lng']],on='city_1', how='right', indicator=True)
test.drop_duplicates().reset_index()

    index                   city_1  visits        lat         lng _merge
0       0                    Paris       8  48.856614    2.352222   both
1     189                Hollywood       7  34.092809 -118.328661   both
2     302                     Rome       5  41.902784   12.496365   both
3     366                    Milan       4  45.464204    9.189982   both
4     400                    Genoa       3  44.405650    8.946256   both
5     405                   Naples       3  40.851775   14.268124   both
6     414             Buenos Aires       3 -34.603684  -58.381559   both
7     492                Las Vegas       3  36.169941 -115.139830   both
8     523                     Reno       3  39.529633 -119.813803   both
9     547                   London       3  51.507351   -0.127758   both
10    658                    Turin       2  45.070312    7.686856   both
11    662                 Florence       2  43.769560   11.255814   both
12    668                  Bologna       2  44.494887   11.342616   both
13    673                  Brescia       2  45.541553   10.211802   both
14    675            New York City       2  40.712775  -74.005973   both
15    733           Rio de Janeiro       2 -22.906847  -43.172897   both
16    776             Barranquilla       2  11.004107  -74.806981   both
17    782                 Kingston       2  18.017874  -76.809904   both
18    811              Mexico City       2  19.432608  -99.133208   both
19    813                 New York       2  40.712775  -74.005973   both
20    818                  Palermo       2  38.115688   13.361267   both
21    823                  Catania       2  37.507877   15.083030   both
22    826            San Francisco       2  37.774929 -122.419415   both
23    852                    Cairo       1  30.044420   31.235712   both
24    857                   Venice       1  45.440847   12.315515   both
25    860                 Piacenza       1  45.052621    9.692984   both
26    861                   Biella       1  45.562884    8.058340   both
27    862                    Belem       1  -1.455729  -48.490178   both
28    864                   Recife       1  -8.052240  -34.928610   both
29    870                Sao Paulo       1 -23.550520  -46.633309   both
..    ...                      ...     ...        ...         ...    ...
60   1235                 Biarritz       1  43.483152   -1.558626   both
61   1240                      Dax       1  43.708608   -1.051945   both
62   1241                Barcelona       1  41.385064    2.173404   both
63   1257              Ventimiglia       1  43.791237    7.607586   both
64   1258  Santa Margherita, Genoa       1  44.325436    9.195443   both
65   1262                Marseille       1  43.296482    5.369780   both
66   1271                     Bern       1  46.947974    7.447447   both
67   1274                   Zurich       1  47.376887    8.541694   both
68   1278                   Altreu       1  47.205557    7.455571   both
69   1279                 Lausanne       1  46.519653    6.632273   both
70   1280                    Basel       1  47.559599    7.588576   both
71   1282                   Sicily       1  37.599994   14.015356   both
72   1283                     Bari       1  41.117143   16.871872   both
73   1285                  Livorno       1  43.548473   10.310567   both
74   1286                  Trieste       1  45.649526   13.776818   both
75   1289                   Padova       1  45.406435   11.876761   both
76   1290                   Varese       1  45.820599    8.825058   both
77   1292                  Bergamo       1  45.698264    9.677270   both
78   1294                   Verona       1  45.438384   10.991622   both
79   1296                 Bordeaux       1  44.837789   -0.579180   both
80   1298                     Oran       1  35.697070   -0.630799   both
81   1300               Casablanca       1  33.573110   -7.589843   both
82   1302                  Chicago       1  41.878114  -87.629798   both
83   1303                   Joliet       1  41.525031  -88.081725   both
84   1304                Vancouver       1  49.282729 -123.120738   both
85   1319          Crystal Bay, NV       1  39.227827 -120.004710   both
86   1329                   Havana       1  23.113592  -82.366596   both
87   1332              Los Angeles       1  34.052234 -118.243685   both
88   1342           San Francisco        1  37.774929 -122.419415   both
89   1343            Beverly Hills       1  34.073620 -118.400356   both

[90 rows x 6 columns]

In [176]:
visits_df

                     city_1  visits
0                     Paris       8
1                 Hollywood       7
2                      Rome       5
3                     Milan       4
4                     Genoa       3
5                    Naples       3
6              Buenos Aires       3
7                 Las Vegas       3
8                      Reno       3
9                    London       3
10                    Turin       2
11                 Florence       2
12                  Bologna       2
13                  Brescia       2
14            New York City       2
15           Rio de Janeiro       2
16             Barranquilla       2
17                 Kingston       2
18              Mexico City       2
19                 New York       2
20                  Palermo       2
21                  Catania       2
22            San Francisco       2
23                    Cairo       1
24                   Venice       1
25                 Piacenza       1
26                   Biella       1
27                    Belem       1
28                   Recife       1
29                Sao Paulo       1
..                      ...     ...
58                 Biarritz       1
59                      Dax       1
60                Barcelona       1
61              Ventimiglia       1
62  Santa Margherita, Genoa       1
63                Marseille       1
64                     Bern       1
65                   Zurich       1
66                   Altreu       1
67                 Lausanne       1
68                    Basel       1
69                   Sicily       1
70                     Bari       1
71                  Livorno       1
72                  Trieste       1
73                   Padova       1
74                   Varese       1
75                  Bergamo       1
76                   Verona       1
77                 Bordeaux       1
78                     Oran       1
79               Casablanca       1
80                  Chicago       1
81                   Joliet       1
82                Vancouver       1
83          Crystal Bay, NV       1
84                   Havana       1
85              Los Angeles       1
86           San Francisco        1
87            Beverly Hills       1

[88 rows x 2 columns]

In [172]:
visits_df.join(df, on='city_1', lsuffix='visits', how='left')

,city_1visits,visits,index,Unnamed: 0,Unnamed: 0.1,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same,location
0,Paris,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Hollywood,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Rome,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Milan,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Genoa,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Naples,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Buenos Aires,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Las Vegas,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Reno,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,London,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Turin,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Florence,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Bologna,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Brescia,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,New York City,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Rio de Janeiro,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Barranquilla,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Kingston,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Mexico City,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,New York,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Palermo,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Catania,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,San Francisco,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cairo,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Venice,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Piacenza,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Biella,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Belem,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Recife,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Sao Paulo,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Biarritz,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Dax,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,Barcelona,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,Ventimiglia,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,"Santa Margherita, Genoa",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Marseille,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,Bern,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Zurich,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Altreu,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Lausanne,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Basel,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Sicily,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,Bari,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Livorno,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Trieste,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Padova,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Varese,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,Bergamo,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,Verona,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,Bordeaux,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,Oran,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Casablanca,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Chicago,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Joliet,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Vancouver,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,"Crystal Bay, NV",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Havana,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Los Angeles,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,San Francisco,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Beverly Hills,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN