In [30]:
import pandas as pd
import numpy as np
from collections import Counter
import geocoder

In [4]:
# read in dataframe
df = pd.read_excel("CURA Dunham 1950-53 .xlsx")

In [21]:
# lowercase columns
df.columns = [x.lower() for x in df.columns]
df.columns = [x.strip() for x in df.columns]
df.columns = [x.replace(" ", "_") for x in df.columns]

In [32]:
g = geocoder.google(df['city_1'][0] + "," + df['country_1'][0])

,date,city_1,country_1,city_2,country_2,working,source
0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
1,1950-01-02,Paris,France,NaN,NaN,y,NaN
2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1
3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2
4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3
5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4
6,1950-01-07,Paris,France,NaN,NaN,y,NaN
7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7"
27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6
29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...
...,...,...,...,...,...,...,...
1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN
1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN
1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN
1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN
1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN
1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN
1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN
1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN
1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5
1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN
1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN
1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN
1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9
1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN
1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN
1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN
1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9
1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN
1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN
1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN
1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN
1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN
1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN
1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN
1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN
1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN
1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN
1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN
1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN
1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN

In [79]:
for i, v in df.iterrows():
#     print(str(v['city_1']) + "," + str(v['country_1']))
    if df['lat'][i] == None:
        try:
            g = geocoder.google(str(v['city_1']) + "," + str(v['country_1']))
            df['lat'][i] = g.lat
            df['lng'][i] = g.lng
        except Exception as e:
            print(e)
            df['lat'][i] = None
            df['lng'][i] = None

c:\python36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

c:\python36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
c:\python36\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
c:\python36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

ERROR - No results found
ERROR - No results found
ERROR - No results found
ERROR - No results found
ERROR - No results found
ERROR - No results found
ERROR - No results found
ERROR - No results found

In [81]:
df.to_csv("g2.csv")

In [82]:
"""
Loop through data and count two things:

Length of stay = number of consecutive days in same city, call it a single 'trip' (may indicate success in an area)

# of returns to an city = number of trips to a city ( may indicate prefrence )
"""

def compare_previous(df, column):
    """
    compare previous row for change in column value
    """
    return df[column].eq(df[column].shift())

def count_duration(trips):
    """
    count number of rows column value stays the same
    """
    return sorted(trips, key= lambda x: x[1], reverse=True)

def count_returns(trips):
    counts = Counter(elem[0] for elem in trips)
    returns = counts.most_common()
    return returns

def trip_duration_count(df, column):
    """
    Initial loop through data counting trips and their date ranges
    
    """
    count = 0
    results = []
    for i, v in df.iterrows():
        min_date = df['date'][i]
        lat = v['lat']
        lng = v['lng']
        print(lat)
        print(lng)

        if v['same'] != False:
            count += 1
            max_date = df['date'][count]
            
#             print(i, v['Date'], v[column])
        else:
#             result = {df[column][i-1]: count}
            max_date = df['date'][i-1]
            min_date = df['date'][i-count]
            
            result = (df[column][i-1] , count, min_date, max_date, df['lat'][i-1], df['lng'][i-1] )
            # just one entry is 1
            if result[1] == 0:
#                 result[df[column][i-1]] = 1
                result = (df[column][i-1] , count+1, min_date, max_date, df['lat'][i-1], df['lng'][i-1])
#             print(result)
            #index of trips dict set here
#             results[len(results)] = result
            results.append(result)
            count = 0
#         print(v['same'], min_date, max_date)
    return results
    #     print(i+1, v['City, Country'], v['same'])
    

df['same'] = compare_previous(df, 'city_1')
#change first entry value to true
df['same'][0] = True

trips = trip_duration_count(df, 'city_1')
durations = count_duration(trips)
returns = count_returns(trips)

c:\python36\lib\site-packages\ipykernel_launcher.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
30.0444196
31.2357116
30.0444196
31.2357116
30.0444196
31.2357116
30.0444196
31.2357116
30.0444196
31.2357116
41.9027835
12.4963655
45.070312
7.686856499999999
45.070312
7.686856499999999
44.4056499
8.946256
44.4056499
8.946256
36.0545737
-95.923037
40.8517746
14.2681244
40.8517746
14.2681244
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
36.0545737
-95.923037
43.7695604
11.2558136
43.7695604
11.2558136
43.7695604
11.2558136
43.7695604
11.2558136
44.494887
11.3426162
44.494887
11.3426162
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4408474
12.3155151
45.4408474
12.3155151
45.4408474
12.3155151
45.4642035
9.189982
45.0526206
9.6929845
45.5415526
10.2118019
45.56288420000001
8.0583397
44.4056499
8.946256
45.4642035
9.189982
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
-1.4557292
-48.4901785
-1.4557292
-48.4901785
-8.0522404
-34.9286096
-8.0522404
-34.9286096
-8.0522404
-34.9286096
-8.0522404
-34.9286096
-8.0522404
-34.9286096
-8.0522404
-34.9286096
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-23.5505199
-46.63330939999999
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-22.9068467
-43.1728965
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.9011127
-56.16453139999999
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-34.6036844
-58.3815591
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
36.0545737
-95.923037
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-33.4488897
-70.6692655
-34.6036844
-58.3815591
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-38.0054771
-57.5426106
-34.6036844
-58.3815591
-34.6036844
-58.3815591
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
None
None
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-12.0463731
-77.042754
-0.1806532
-78.4678382
-0.1806532
-78.4678382
-0.1806532
-78.4678382

-0.1806532
-78.4678382
3.4516467
-76.5319854
3.4516467
-76.5319854
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
4.710988599999999
-74.072092
6.244203
-75.5812119
6.244203
-75.5812119
11.0041072
-74.80698129999999
11.0041072
-74.80698129999999
11.0041072
-74.80698129999999
10.3910485
-75.4794257
11.0041072
-74.80698129999999
11.0041072
-74.80698129999999
11.0041072
-74.80698129999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
10.4805937
-66.90360629999999
18.0178743
-76.8099041
18.0178743
-76.8099041
18.5138139
-72.2881907
18.5138139
-72.2881907
18.5138139
-72.2881907
18.5138139
-72.2881907
18.5138139
-72.2881907
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.0178743
-76.8099041
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
None
None
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
18.594395
-72.3074326
None
None
19.4326077
-99.133208
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
20.6596988
-103.3496092
19.4326077
-99.133208
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
36.0545737
-95.923037
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
40.7127753
-74.0059728
40.7127753
-74.0059728
40.7127753
-74.0059728
36.0545737
-95.923037
40.7127753
-74.0059728
48.954408
-54.6103488
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
None
None
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
None
None
None
None
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
54.976479
-5.0268868
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
54.59728500000001
-5.93012
53.3498053
-6.2603097
53.3498053
-6.2603097
53.3498053
-6.2603097
53.3498053
-6.2603097
53.3498053
-6.2603097
53.3498053
-6.2603097
53.3498053
-6.2603097
51.5073509
-0.1277583
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
50.719164
-1.880769
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.95478319999999
-1.1581086
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
52.48624299999999
-1.890401
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.454513
-2.58791
51.5073509
-0.1277583
51.5073509
-0.1277583
51.5073509
-0.1277583
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
55.6760968
12.5683372
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
46.131859
3.425488
46.131859
3.425488
46.227638
2.213749
46.227638
2.213749
46.227638
2.213749
43.5691905
7.1123854
46.227638
2.213749
43.296482
5.36978
46.227638
2.213749
43.7101728
7.261953200000001
46.227638
2.213749
46.227638
2.213749
44.652297
-1.1785016
44.652297
-1.1785016
46.227638
2.213749
43.4831519
-1.558626
43.4831519
-1.558626
43.4831519
-1.558626
43.4831519
-1.558626
43.4831519
-1.558626
35.2109787
-101.8667601
43.708608
-1.051945
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
36.0545737
-95.923037
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
41.3850639
2.1734035
43.7912366
7.6075864
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982

45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
45.4642035
9.189982
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
38.1156879
13.3612671
38.1156879
13.3612671
37.5078772
15.0830304
37.5078772
15.0830304
40.8517746
14.2681244
40.8517746
14.2681244
40.8517746
14.2681244
45.070312
7.686856499999999
45.070312
7.686856499999999
44.4056499
8.946256
44.4056499
8.946256
44.3254364
9.1954432
44.3254364
9.1954432
44.3254364
9.1954432
44.3254364
9.1954432
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
43.296482
5.36978
46.9479739
7.4474468
46.9479739
7.4474468
46.9479739
7.4474468
47.3768866
8.541694
47.3768866
8.541694
47.3768866
8.541694
47.3768866
8.541694
36.0545737
-95.923037
47.205557
7.455571
46.5196535
6.6322734
47.5595986
7.5885761
47.5595986
7.5885761
41.9027835
12.4963655
41.9027835
12.4963655
37.5999938
14.0153557
38.1156879
13.3612671
38.1156879
13.3612671
38.1156879
13.3612671
37.5078772
15.0830304
36.0545737
-95.923037
41.1171432
16.8718715
41.1171432
16.8718715
40.8517746
14.2681244
40.8517746
14.2681244
40.8517746
14.2681244
40.8517746
14.2681244
43.548473
10.3105674
43.7695604
11.2558136
43.7695604
11.2558136
45.6495264
13.7768182
45.6495264
13.7768182
45.6495264
13.7768182
45.4064349
11.8767611
45.5415526
10.2118019
45.82059890000001
8.8250576
45.82059890000001
8.8250576
45.6982642
9.6772698
45.6982642
9.6772698
45.43838419999999
10.9916215
45.43838419999999
10.9916215
44.494887
11.3426162
44.494887
11.3426162
44.494887
11.3426162
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
35.2109787
-101.8667601
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
44.837789
-0.57918
44.837789
-0.57918
36.0545737
-95.923037
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
48.856614
2.3522219
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.6970697
-0.6307988
35.6970697
-0.6307988
35.2109787
-101.8667601
35.2109787
-101.8667601
33.5731104
-7.589843399999999
33.5731104
-7.589843399999999
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
48.856614
2.3522219
48.856614
2.3522219
40.7127753
-74.0059728
40.7127753
-74.0059728
41.8781136
-87.6297982
35.2109787
-101.8667601
35.2109787
-101.8667601
41.525031
-88.0817251
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
None
None
35.2109787
-101.8667601
35.2109787
-101.8667601
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
34.0928092
-118.3286614
36.1699412
-115.1398296
36.1699412
-115.1398296
36.1699412
-115.1398296
34.0928092
-118.3286614
34.0928092
-118.3286614
None
None
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
34.0928092
-118.3286614
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
39.5296329
-119.8138027
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
49.2827291
-123.1207375
35.2109787
-101.8667601
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
39.2278272
-120.0047095
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
34.0928092
-118.3286614
36.0545737
-95.923037
36.0545737
-95.923037
23.1135925
-82.3665956
23.1135925
-82.3665956
23.1135925
-82.3665956
36.0545737
-95.923037
36.0545737
-95.923037
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
34.0522342
-118.2436849
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787

-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
37.7749295
-122.4194155
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
34.0736204
-118.4003563
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
35.2109787
-101.8667601
40.7127753
-74.0059728
48.856614
2.3522219
35.2109787
-101.8667601
35.2109787
-101.8667601
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655
41.9027835
12.4963655

In [89]:
durations

[('London',
  106,
  Timestamp('1952-01-06 00:00:00'),
  Timestamp('1952-04-20 00:00:00'),
  51.5073509,
  -0.1277583),
 ('Paris',
  88,
  Timestamp('1951-10-09 00:00:00'),
  Timestamp('1952-01-04 00:00:00'),
  48.856614,
  2.3522219),
 ('Port au Prince',
  81,
  Timestamp('1951-04-17 00:00:00'),
  Timestamp('1951-07-06 00:00:00'),
  18.594395,
  -72.3074326),
 ('Buenos Aires',
  74,
  Timestamp('1950-09-01 00:00:00'),
  Timestamp('1950-11-13 00:00:00'),
  -34.6036844,
  -58.3815591),
 ('New York City',
  55,
  Timestamp('1950-04-12 00:00:00'),
  Timestamp('1950-06-05 00:00:00'),
  40.7127753,
  -74.0059728),
 ('Paris',
  38,
  Timestamp('1953-01-09 00:00:00'),
  Timestamp('1953-02-15 00:00:00'),
  48.856614,
  2.3522219),
 ('Hollywood',
  38,
  Timestamp('1953-08-29 00:00:00'),
  Timestamp('1953-10-05 00:00:00'),
  34.0928092,
  -118.3286614),
 ('Paris',
  30,
  Timestamp('1950-01-01 00:00:00'),
  Timestamp('1950-01-30 00:00:00'),
  48.856614,
  2.3522219),
 ('Hollywood',
  29,
  Timestamp('1953-07-04 00:00:00'),
  Timestamp('1953-08-01 00:00:00'),
  34.0928092,
  -118.3286614),
 ('Rio de Janeiro',
  26,
  Timestamp('1950-06-15 00:00:00'),
  Timestamp('1950-07-10 00:00:00'),
  -22.9068467,
  -43.1728965),
 ('Kingston',
  26,
  Timestamp('1951-03-21 00:00:00'),
  Timestamp('1951-04-15 00:00:00'),
  18.0178743,
  -76.8099041),
 ('Copenhagen',
  24,
  Timestamp('1952-07-11 00:00:00'),
  Timestamp('1952-08-03 00:00:00'),
  55.6760968,
  12.5683372),
 ('Lima',
  23,
  Timestamp('1951-01-07 00:00:00'),
  Timestamp('1951-01-29 00:00:00'),
  -12.0463731,
  -77.042754),
 ('Port-au-Prince',
  22,
  Timestamp('1951-07-08 00:00:00'),
  Timestamp('1951-07-29 00:00:00'),
  None,
  None),
 ('San Francisco',
  22,
  Timestamp('1953-05-03 00:00:00'),
  Timestamp('1953-05-24 00:00:00'),
  37.7749295,
  -122.4194155),
 ('Mar del Plata',
  21,
  Timestamp('1950-12-14 00:00:00'),
  Timestamp('1951-01-03 00:00:00'),
  -38.0054771,
  -57.5426106),
 ('Hollywood',
  21,
  Timestamp('1953-04-11 00:00:00'),
  Timestamp('1953-05-01 00:00:00'),
  34.0928092,
  -118.3286614),
 ('Milan',
  19,
  Timestamp('1950-03-02 00:00:00'),
  Timestamp('1950-03-20 00:00:00'),
  45.4642035,
  9.189982),
 ('Sao Paulo',
  18,
  Timestamp('1950-07-12 00:00:00'),
  Timestamp('1950-07-29 00:00:00'),
  -23.5505199,
  -46.63330939999999),
 ('Santiago',
  17,
  Timestamp('1950-11-25 00:00:00'),
  Timestamp('1950-12-11 00:00:00'),
  -33.4488897,
  -70.6692655),
 ('Las Vegas',
  17,
  Timestamp('1951-08-13 00:00:00'),
  Timestamp('1951-08-29 00:00:00'),
  36.1699412,
  -115.1398296),
 ('Rio de Janeiro',
  15,
  Timestamp('1950-07-31 00:00:00'),
  Timestamp('1950-08-14 00:00:00'),
  -22.9068467,
  -43.1728965),
 ('Montevideo',
  15,
  Timestamp('1950-08-16 00:00:00'),
  Timestamp('1950-08-30 00:00:00'),
  -34.9011127,
  -56.16453139999999),
 ('Barcelona',
  15,
  Timestamp('1952-09-16 00:00:00'),
  Timestamp('1952-09-30 00:00:00'),
  41.3850639,
  2.1734035),
 ('Bogota',
  14,
  Timestamp('1951-02-06 00:00:00'),
  Timestamp('1951-02-19 00:00:00'),
  4.710988599999999,
  -74.072092),
 ('Vancouver',
  14,
  Timestamp('1953-08-03 00:00:00'),
  Timestamp('1953-08-16 00:00:00'),
  49.2827291,
  -123.1207375),
 ('Nottingham',
  13,
  Timestamp('1952-05-27 00:00:00'),
  Timestamp('1952-06-08 00:00:00'),
  52.95478319999999,
  -1.1581086),
 ('Birmingham',
  13,
  Timestamp('1952-06-10 00:00:00'),
  Timestamp('1952-06-22 00:00:00'),
  52.48624299999999,
  -1.890401),
 ('Bristol',
  13,
  Timestamp('1952-06-24 00:00:00'),
  Timestamp('1952-07-06 00:00:00'),
  51.454513,
  -2.58791),
 ('Belfast',
  12,
  Timestamp('1952-04-23 00:00:00'),
  Timestamp('1952-05-04 00:00:00'),
  54.59728500000001,
  -5.93012),
 ('Bournemouth',
  12,
  Timestamp('1952-05-14 00:00:00'),
  Timestamp('1952-05-25 00:00:00'),
  50.719164,
  -1.880769),
 ('Paris',
  11,
  Timestamp('1950-03-31 00:00:00'),
  Timestamp('1950-04-10 00:00:00'),
  48.856614,
  2.3522219),
 ('Caracas',
  11,
  Timestamp('1951-03-02 00:00:00'),
  Timestamp('1951-03-12 00:00:00'),
  10.4805937,
  -66.90360629999999),
 ('Milan',
  11,
  Timestamp('1952-10-03 00:00:00'),
  Timestamp('1952-10-13 00:00:00'),
  45.4642035,
  9.189982),
 ('Guadalajara',
  10,
  Timestamp('1951-08-01 00:00:00'),
  Timestamp('1951-08-10 00:00:00'),
  20.6596988,
  -103.3496092),
 ('Hollywood',
  10,
  Timestamp('1951-09-17 00:00:00'),
  Timestamp('1951-09-26 00:00:00'),
  34.0928092,
  -118.3286614),
 ('Las Vegas',
  9,
  Timestamp('1953-05-26 00:00:00'),
  Timestamp('1953-06-03 00:00:00'),
  36.1699412,
  -115.1398296),
 ('Reno',
  9,
  Timestamp('1953-06-24 00:00:00'),
  Timestamp('1953-07-02 00:00:00'),
  39.5296329,
  -119.8138027),
 ('Crystal Bay, NV',
  9,
  Timestamp('1953-08-19 00:00:00'),
  Timestamp('1953-08-27 00:00:00'),
  39.2278272,
  -120.0047095),
 ('Los Angeles',
  9,
  Timestamp('1953-10-14 00:00:00'),
  Timestamp('1953-10-22 00:00:00'),
  34.0522342,
  -118.2436849),
 ('Rome',
  8,
  Timestamp('1950-02-14 00:00:00'),
  Timestamp('1950-02-21 00:00:00'),
  41.9027835,
  12.4963655),
 ('Reno',
  8,
  Timestamp('1951-08-31 00:00:00'),
  Timestamp('1951-09-07 00:00:00'),
  39.5296329,
  -119.8138027),
 ('Marseille',
  8,
  Timestamp('1952-11-06 00:00:00'),
  Timestamp('1952-11-13 00:00:00'),
  43.296482,
  5.36978),
 ('Paris',
  8,
  Timestamp('1953-02-25 00:00:00'),
  Timestamp('1953-03-04 00:00:00'),
  48.856614,
  2.3522219),
 ('Hollywood',
  8,
  Timestamp('1953-06-09 00:00:00'),
  Timestamp('1953-06-16 00:00:00'),
  34.0928092,
  -118.3286614),
 ('Dublin',
  6,
  Timestamp('1952-05-06 00:00:00'),
  Timestamp('1952-05-11 00:00:00'),
  53.3498053,
  -6.2603097),
 ('Paris',
  6,
  Timestamp('1952-08-05 00:00:00'),
  Timestamp('1952-08-10 00:00:00'),
  48.856614,
  2.3522219),
 ('Rome',
  6,
  Timestamp('1952-10-15 00:00:00'),
  Timestamp('1952-10-20 00:00:00'),
  41.9027835,
  12.4963655),
 ('Recife',
  5,
  Timestamp('1950-06-09 00:00:00'),
  Timestamp('1950-06-13 00:00:00'),
  -8.0522404,
  -34.9286096),
 ('Rome',
  5,
  Timestamp('1953-01-02 00:00:00'),
  Timestamp('1953-01-06 00:00:00'),
  41.9027835,
  12.4963655),
 ('Cairo',
  4,
  Timestamp('1950-02-01 00:00:00'),
  Timestamp('1950-02-04 00:00:00'),
  30.0444196,
  31.2357116),
 ('Petion-Ville',
  4,
  Timestamp('1951-03-16 00:00:00'),
  Timestamp('1951-03-19 00:00:00'),
  18.5138139,
  -72.2881907),
 ('Biarritz',
  4,
  Timestamp('1952-08-27 00:00:00'),
  Timestamp('1952-08-30 00:00:00'),
  43.4831519,
  -1.558626),
 ('Reno',
  4,
  Timestamp('1953-06-18 00:00:00'),
  Timestamp('1953-06-21 00:00:00'),
  39.5296329,
  -119.8138027),
 ('Florence',
  3,
  Timestamp('1950-02-24 00:00:00'),
  Timestamp('1950-02-26 00:00:00'),
  43.7695604,
  11.2558136),
 ('Quito',
  3,
  Timestamp('1951-01-31 00:00:00'),
  Timestamp('1951-02-02 00:00:00'),
  -0.1806532,
  -78.4678382),
 ('Santa Margherita, Genoa',
  3,
  Timestamp('1952-11-02 00:00:00'),
  Timestamp('1952-11-04 00:00:00'),
  44.3254364,
  9.1954432),
 ('Zurich',
  3,
  Timestamp('1952-11-18 00:00:00'),
  Timestamp('1952-11-20 00:00:00'),
  47.3768866,
  8.541694),
 ('Naples',
  3,
  Timestamp('1952-12-07 00:00:00'),
  Timestamp('1952-12-09 00:00:00'),
  40.8517746,
  14.2681244),
 ('Venice',
  2,
  Timestamp('1950-03-22 00:00:00'),
  Timestamp('1950-03-23 00:00:00'),
  45.4408474,
  12.3155151),
 ('Barranquilla',
  2,
  Timestamp('1951-02-23 00:00:00'),
  Timestamp('1951-02-24 00:00:00'),
  11.0041072,
  -74.80698129999999),
 ('Barranquilla',
  2,
  Timestamp('1951-02-27 00:00:00'),
  Timestamp('1951-02-28 00:00:00'),
  11.0041072,
  -74.80698129999999),
 ('New York',
  2,
  Timestamp('1951-10-03 00:00:00'),
  Timestamp('1951-10-04 00:00:00'),
  40.7127753,
  -74.0059728),
 ('London',
  2,
  Timestamp('1952-07-08 00:00:00'),
  Timestamp('1952-07-09 00:00:00'),
  51.5073509,
  -0.1277583),
 ('Naples',
  2,
  Timestamp('1952-10-26 00:00:00'),
  Timestamp('1952-10-27 00:00:00'),
  40.8517746,
  14.2681244),
 ('Bern',
  2,
  Timestamp('1952-11-15 00:00:00'),
  Timestamp('1952-11-16 00:00:00'),
  46.9479739,
  7.4474468),
 ('Palermo',
  2,
  Timestamp('1952-11-30 00:00:00'),
  Timestamp('1952-12-01 00:00:00'),
  38.1156879,
  13.3612671),
 ('Trieste',
  2,
  Timestamp('1952-12-14 00:00:00'),
  Timestamp('1952-12-15 00:00:00'),
  45.6495264,
  13.7768182),
 ('Bologna',
  2,
  Timestamp('1952-12-25 00:00:00'),
  Timestamp('1952-12-26 00:00:00'),
  44.494887,
  11.3426162),
 ('Las Vegas',
  2,
  Timestamp('1953-06-06 00:00:00'),
  Timestamp('1953-06-07 00:00:00'),
  36.1699412,
  -115.1398296),
 ('Havana',
  2,
  Timestamp('1953-10-09 00:00:00'),
  Timestamp('1953-10-10 00:00:00'),
  23.1135925,
  -82.3665956),
 ('San Francisco',
  2,
  Timestamp('1953-11-02 00:00:00'),
  Timestamp('1953-11-03 00:00:00'),
  37.7749295,
  -122.4194155),
 ('Rome',
  1,
  Timestamp('1950-02-06 00:00:00'),
  Timestamp('1950-02-05 00:00:00'),
  41.9027835,
  12.4963655),
 ('Turin',
  1,
  Timestamp('1950-02-07 00:00:00'),
  Timestamp('1950-02-07 00:00:00'),
  45.070312,
  7.686856499999999),
 ('Genoa',
  1,
  Timestamp('1950-02-09 00:00:00'),
  Timestamp('1950-02-09 00:00:00'),
  44.4056499,
  8.946256),
 (nan,
  1,
  Timestamp('1950-02-11 00:00:00'),
  Timestamp('1950-02-10 00:00:00'),
  36.0545737,
  -95.923037),
 ('Naples',
  1,
  Timestamp('1950-02-12 00:00:00'),
  Timestamp('1950-02-12 00:00:00'),
  40.8517746,
  14.2681244),
 (nan,
  1,
  Timestamp('1950-02-23 00:00:00'),
  Timestamp('1950-02-22 00:00:00'),
  36.0545737,
  -95.923037),
 ('Bologna',
  1,
  Timestamp('1950-02-28 00:00:00'),
  Timestamp('1950-02-28 00:00:00'),
  44.494887,
  11.3426162),
 ('Milan',
  1,
  Timestamp('1950-03-25 00:00:00'),
  Timestamp('1950-03-24 00:00:00'),
  45.4642035,
  9.189982),
 ('Piacenza',
  1,
  Timestamp('1950-03-26 00:00:00'),
  Timestamp('1950-03-25 00:00:00'),
  45.0526206,
  9.6929845),
 ('Brescia',
  1,
  Timestamp('1950-03-27 00:00:00'),
  Timestamp('1950-03-26 00:00:00'),
  45.5415526,
  10.2118019),
 ('Biella',
  1,
  Timestamp('1950-03-28 00:00:00'),
  Timestamp('1950-03-27 00:00:00'),
  45.56288420000001,
  8.0583397),
 ('Genoa',
  1,
  Timestamp('1950-03-29 00:00:00'),
  Timestamp('1950-03-28 00:00:00'),
  44.4056499,
  8.946256),
 ('Milan',
  1,
  Timestamp('1950-03-30 00:00:00'),
  Timestamp('1950-03-29 00:00:00'),
  45.4642035,
  9.189982),
 ('Belem',
  1,
  Timestamp('1950-06-07 00:00:00'),
  Timestamp('1950-06-07 00:00:00'),
  -1.4557292,
  -48.4901785),
 (nan,
  1,
  Timestamp('1950-11-15 00:00:00'),
  Timestamp('1950-11-14 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-16 00:00:00'),
  Timestamp('1950-11-15 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-17 00:00:00'),
  Timestamp('1950-11-16 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-18 00:00:00'),
  Timestamp('1950-11-17 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-19 00:00:00'),
  Timestamp('1950-11-18 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-20 00:00:00'),
  Timestamp('1950-11-19 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-21 00:00:00'),
  Timestamp('1950-11-20 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-22 00:00:00'),
  Timestamp('1950-11-21 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-23 00:00:00'),
  Timestamp('1950-11-22 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1950-11-24 00:00:00'),
  Timestamp('1950-11-23 00:00:00'),
  36.0545737,
  -95.923037),
 ('Buenos Aires',
  1,
  Timestamp('1950-12-13 00:00:00'),
  Timestamp('1950-12-12 00:00:00'),
  -34.6036844,
  -58.3815591),
 ('Buenos Aires',
  1,
  Timestamp('1951-01-05 00:00:00'),
  Timestamp('1951-01-05 00:00:00'),
  -34.6036844,
  -58.3815591),
 ('Cali',
  1,
  Timestamp('1951-02-04 00:00:00'),
  Timestamp('1951-02-04 00:00:00'),
  3.4516467,
  -76.5319854),
 ('Medellin',
  1,
  Timestamp('1951-02-21 00:00:00'),
  Timestamp('1951-02-21 00:00:00'),
  6.244203,
  -75.5812119),
 ('Cartagena',
  1,
  Timestamp('1951-02-26 00:00:00'),
  Timestamp('1951-02-25 00:00:00'),
  10.3910485,
  -75.4794257),
 ('Kingston',
  1,
  Timestamp('1951-03-14 00:00:00'),
  Timestamp('1951-03-14 00:00:00'),
  18.0178743,
  -76.8099041),
 ('Mexico City',
  1,
  Timestamp('1951-07-31 00:00:00'),
  Timestamp('1951-07-30 00:00:00'),
  19.4326077,
  -99.133208),
 ('Mexico City',
  1,
  Timestamp('1951-08-12 00:00:00'),
  Timestamp('1951-08-11 00:00:00'),
  19.4326077,
  -99.133208),
 (nan,
  1,
  Timestamp('1951-09-09 00:00:00'),
  Timestamp('1951-09-08 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-10 00:00:00'),
  Timestamp('1951-09-09 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-11 00:00:00'),
  Timestamp('1951-09-10 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-12 00:00:00'),
  Timestamp('1951-09-11 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-13 00:00:00'),
  Timestamp('1951-09-12 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1951-09-14 00:00:00'),
  Timestamp('1951-09-13 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-15 00:00:00'),
  Timestamp('1951-09-14 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-16 00:00:00'),
  Timestamp('1951-09-15 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-28 00:00:00'),
  Timestamp('1951-09-27 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-29 00:00:00'),
  Timestamp('1951-09-28 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-09-30 00:00:00'),
  Timestamp('1951-09-29 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-10-01 00:00:00'),
  Timestamp('1951-09-30 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-10-02 00:00:00'),
  Timestamp('1951-10-01 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1951-10-06 00:00:00'),
  Timestamp('1951-10-05 00:00:00'),
  36.0545737,
  -95.923037),
 ('New York',
  1,
  Timestamp('1951-10-07 00:00:00'),
  Timestamp('1951-10-06 00:00:00'),
  40.7127753,
  -74.0059728),
 ('Gander',
  1,
  Timestamp('1951-10-08 00:00:00'),
  Timestamp('1951-10-07 00:00:00'),
  48.954408,
  -54.6103488),
 ('Cairnryan',
  1,
  Timestamp('1952-04-22 00:00:00'),
  Timestamp('1952-04-21 00:00:00'),
  54.976479,
  -5.0268868),
 ('London',
  1,
  Timestamp('1952-05-13 00:00:00'),
  Timestamp('1952-05-12 00:00:00'),
  51.5073509,
  -0.1277583),
 ('Vichy',
  1,
  Timestamp('1952-08-12 00:00:00'),
  Timestamp('1952-08-12 00:00:00'),
  46.131859,
  3.425488),
 (nan,
  1,
  Timestamp('1952-08-14 00:00:00'),
  Timestamp('1952-08-13 00:00:00'),
  46.227638,
  2.213749),
 (nan,
  1,
  Timestamp('1952-08-15 00:00:00'),
  Timestamp('1952-08-14 00:00:00'),
  46.227638,
  2.213749),
 (nan,
  1,
  Timestamp('1952-08-16 00:00:00'),
  Timestamp('1952-08-15 00:00:00'),
  46.227638,
  2.213749),
 ('Juan-les-Pins',
  1,
  Timestamp('1952-08-17 00:00:00'),
  Timestamp('1952-08-16 00:00:00'),
  43.5691905,
  7.1123854),
 (nan,
  1,
  Timestamp('1952-08-18 00:00:00'),
  Timestamp('1952-08-17 00:00:00'),
  46.227638,
  2.213749),
 ('Marseille?',
  1,
  Timestamp('1952-08-19 00:00:00'),
  Timestamp('1952-08-18 00:00:00'),
  43.296482,
  5.36978),
 (nan,
  1,
  Timestamp('1952-08-20 00:00:00'),
  Timestamp('1952-08-19 00:00:00'),
  46.227638,
  2.213749),
 ('Nice',
  1,
  Timestamp('1952-08-21 00:00:00'),
  Timestamp('1952-08-20 00:00:00'),
  43.7101728,
  7.261953200000001),
 (nan,
  1,
  Timestamp('1952-08-22 00:00:00'),
  Timestamp('1952-08-21 00:00:00'),
  46.227638,
  2.213749),
 (nan,
  1,
  Timestamp('1952-08-23 00:00:00'),
  Timestamp('1952-08-22 00:00:00'),
  46.227638,
  2.213749),
 ('Arachon',
  1,
  Timestamp('1952-08-24 00:00:00'),
  Timestamp('1952-08-24 00:00:00'),
  44.652297,
  -1.1785016),
 (nan,
  1,
  Timestamp('1952-08-26 00:00:00'),
  Timestamp('1952-08-25 00:00:00'),
  46.227638,
  2.213749),
 (nan,
  1,
  Timestamp('1952-09-01 00:00:00'),
  Timestamp('1952-08-31 00:00:00'),
  35.2109787,
  -101.8667601),
 ('Dax',
  1,
  Timestamp('1952-09-02 00:00:00'),
  Timestamp('1952-09-01 00:00:00'),
  43.708608,
  -1.051945),
 (nan,
  1,
  Timestamp('1952-09-03 00:00:00'),
  Timestamp('1952-09-02 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1952-09-04 00:00:00'),
  Timestamp('1952-09-03 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1952-09-05 00:00:00'),
  Timestamp('1952-09-04 00:00:00'),
  35.2109787,
  -101.8667601),
 (nan,
  1,
  Timestamp('1952-09-06 00:00:00'),
  Timestamp('1952-09-05 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-07 00:00:00'),
  Timestamp('1952-09-06 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-08 00:00:00'),
  Timestamp('1952-09-07 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-09 00:00:00'),
  Timestamp('1952-09-08 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-10 00:00:00'),
  Timestamp('1952-09-09 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-11 00:00:00'),
  Timestamp('1952-09-10 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-12 00:00:00'),
  Timestamp('1952-09-11 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-13 00:00:00'),
  Timestamp('1952-09-12 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-14 00:00:00'),
  Timestamp('1952-09-13 00:00:00'),
  36.0545737,
  -95.923037),
 (nan,
  1,
  Timestamp('1952-09-15 00:00:00'),
  Timestamp('1952-09-14 00:00:00'),
  36.0545737,
  -95.923037),
 ('Ventimiglia',
  1,
  Timestamp('1952-10-02 00:00:00'),
  Timestamp('1952-10-01 00:00:00'),
  43.7912366,
  7.6075864),
 ('Palermo',
  1,
  Timestamp('1952-10-22 00:00:00'),
  Timestamp('1952-10-22 00:00:00'),
  38.1156879,
  13.3612671),
 ('Catania',
  1,
  Timestamp('1952-10-24 00:00:00'),
  Timestamp('1952-10-24 00:00:00'),
  37.5078772,
  15.0830304),
 ('Turin',
  1,
  Timestamp('1952-10-29 00:00:00'),
  Timestamp('1952-10-29 00:00:00'),
  45.070312,
  7.686856499999999),
 ('Genoa',
  1,
  Timestamp('1952-10-31 00:00:00'),
  Timestamp('1952-10-31 00:00:00'),
  44.4056499,
  8.946256),
 (nan,
  1,
  Timestamp('1952-11-22 00:00:00'),
  Timestamp('1952-11-21 00:00:00'),
  36.0545737,
  -95.923037),
 ('Altreu',
  1,
  Timestamp('1952-11-23 00:00:00'),
  Timestamp('1952-11-22 00:00:00'),
  47.205557,
  7.455571),
 ('Lausanne',
  1,
  Timestamp('1952-11-24 00:00:00'),
  Timestamp('1952-11-23 00:00:00'),
  46.5196535,
  6.6322734),
 ('Basel',
  1,
  Timestamp('1952-11-25 00:00:00'),
  Timestamp('1952-11-25 00:00:00'),
  47.5595986,
  7.5885761),
 ('Rome',
  1,
  Timestamp('1952-11-27 00:00:00'),
  Timestamp('1952-11-27 00:00:00'),
  41.9027835,
  12.4963655),
 ('Sicily',
  1,
  Timestamp('1952-11-29 00:00:00'),
  Timestamp('1952-11-28 00:00:00'),
  37.5999938,
  14.0153557),
 ('Catania',
  1,
  Timestamp('1952-12-03 00:00:00'),
  Timestamp('1952-12-02 00:00:00'),
  37.5078772,
  15.0830304),
 (nan,
  1,
  Timestamp('1952-12-04 00:00:00'),
  Timestamp('1952-12-03 00:00:00'),
  36.0545737,
  -95.923037),
 ('Bari',
  1,
  Timestamp('1952-12-05 00:00:00'),
  Timestamp('1952-12-05 00:00:00'),
  41.1171432,
  16.8718715),
 ('Livorno',
  1,
  Timestamp('1952-12-11 00:00:00'),
  Timestamp('1952-12-10 00:00:00'),
  43.548473,
  10.3105674),
 ('Florence',
  1,
  Timestamp('1952-12-12 00:00:00'),
  Timestamp('1952-12-12 00:00:00'),
  43.7695604,
  11.2558136),
 ('Padova',
  1,
  Timestamp('1952-12-17 00:00:00'),
  Timestamp('1952-12-16 00:00:00'),
  45.4064349,
  11.8767611),
 ('Brescia',
  1,
  Timestamp('1952-12-18 00:00:00'),
  Timestamp('1952-12-17 00:00:00'),
  45.5415526,
  10.2118019),
 ('Varese',
  1,
  Timestamp('1952-12-19 00:00:00'),

In [88]:
df

,date,city_1,country_1,city_2,country_2,working,source,lat,lng,same
0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
1,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True
2,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True
3,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True
4,1950-01-05,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 3,48.8566,2.35222,True
5,1950-01-06,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 4,48.8566,2.35222,True
6,1950-01-07,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True
7,1950-01-08,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
8,1950-01-09,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
9,1950-01-10,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
10,1950-01-11,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
11,1950-01-12,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
12,1950-01-13,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
13,1950-01-14,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
14,1950-01-15,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
15,1950-01-16,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
16,1950-01-17,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
17,1950-01-18,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
18,1950-01-19,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
19,1950-01-20,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
20,1950-01-21,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
21,1950-01-22,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
22,1950-01-23,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
23,1950-01-24,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
24,1950-01-25,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
25,1950-01-26,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
26,1950-01-27,Paris,France,NaN,NaN,y,"SIU Box 14 folder 6, 7",48.8566,2.35222,True
27,1950-01-28,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
28,1950-01-29,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True
29,1950-01-30,Paris,France,Cairo,Egypt,n,TWA flight timetable Nov. 1949 from the collec...,48.8566,2.35222,True
...,...,...,...,...,...,...,...,...,...,...
1431,1953-12-02,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1432,1953-12-03,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1433,1953-12-04,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1434,1953-12-05,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1435,1953-12-06,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1436,1953-12-07,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1437,1953-12-08,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1438,1953-12-09,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1439,1953-12-10,Rome,Italy,NaN,NaN,y,SIU Box 39 folder 5,41.9028,12.4964,True
1440,1953-12-11,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1441,1953-12-12,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1442,1953-12-13,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1443,1953-12-14,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.9028,12.4964,True
1444,1953-12-15,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1445,1953-12-16,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1446,1953-12-17,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1447,1953-12-18,Rome,Italy,NaN,NaN,y,SIU Box 16 folder 9,41.9028,12.4964,True
1448,1953-12-19,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1449,1953-12-20,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1450,1953-12-21,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1451,1953-12-22,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1452,1953-12-23,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1453,1953-12-24,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1454,1953-12-25,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1455,1953-12-26,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1456,1953-12-27,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1457,1953-12-28,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1458,1953-12-29,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1459,1953-12-30,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True
1460,1953-12-31,Rome,Italy,NaN,NaN,y,NaN,41.9028,12.4964,True

In [102]:
durations_df = pd.DataFrame.from_records(durations, columns=['city_1', 'duration_days', 'min_date', 'max_date', 'lat', 'lng'] )
returns_df = pd.DataFrame.from_records(returns, columns=['city_1', 'returns'])

durations_df.to_csv('durations.csv')
returns_df.to_csv('returns.csv')

In [106]:
df_duration_merge = pd.merge(df, durations_df, left_on = 'city_1', right_on = 'city_1')

In [108]:
df_duration_returns_merge = pd.merge(df_duration_merge, returns_df, left_on = 'city_1', right_on = 'city_1')

In [110]:
df_duration_returns_merge.to_csv('merged.csv')

In [111]:
df_duration_returns_merge

,date,city_1,country_1,city_2,country_2,working,source,lat_x,lng_x,same,duration_days,min_date,max_date,lat_y,lng_y,returns
0,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,88,1951-10-09,1952-01-04,48.856614,2.352222,8
1,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,38,1953-01-09,1953-02-15,48.856614,2.352222,8
2,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,30,1950-01-01,1950-01-30,48.856614,2.352222,8
3,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,11,1950-03-31,1950-04-10,48.856614,2.352222,8
4,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,8,1953-02-25,1953-03-04,48.856614,2.352222,8
5,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,6,1952-08-05,1952-08-10,48.856614,2.352222,8
6,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,1,1953-03-27,1953-03-27,48.856614,2.352222,8
7,1950-01-01,Paris,France,NaN,NaN,y,SIU Box 14 folder 6,48.8566,2.35222,True,1,1953-11-21,1953-11-20,48.856614,2.352222,8
8,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,88,1951-10-09,1952-01-04,48.856614,2.352222,8
9,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,38,1953-01-09,1953-02-15,48.856614,2.352222,8
10,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,30,1950-01-01,1950-01-30,48.856614,2.352222,8
11,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,11,1950-03-31,1950-04-10,48.856614,2.352222,8
12,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,8,1953-02-25,1953-03-04,48.856614,2.352222,8
13,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,6,1952-08-05,1952-08-10,48.856614,2.352222,8
14,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,1,1953-03-27,1953-03-27,48.856614,2.352222,8
15,1950-01-02,Paris,France,NaN,NaN,y,NaN,48.8566,2.35222,True,1,1953-11-21,1953-11-20,48.856614,2.352222,8
16,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,88,1951-10-09,1952-01-04,48.856614,2.352222,8
17,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,38,1953-01-09,1953-02-15,48.856614,2.352222,8
18,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,30,1950-01-01,1950-01-30,48.856614,2.352222,8
19,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,11,1950-03-31,1950-04-10,48.856614,2.352222,8
20,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,8,1953-02-25,1953-03-04,48.856614,2.352222,8
21,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,6,1952-08-05,1952-08-10,48.856614,2.352222,8
22,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,1,1953-03-27,1953-03-27,48.856614,2.352222,8
23,1950-01-03,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 1,48.8566,2.35222,True,1,1953-11-21,1953-11-20,48.856614,2.352222,8
24,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,88,1951-10-09,1952-01-04,48.856614,2.352222,8
25,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,38,1953-01-09,1953-02-15,48.856614,2.352222,8
26,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,30,1950-01-01,1950-01-30,48.856614,2.352222,8
27,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,11,1950-03-31,1950-04-10,48.856614,2.352222,8
28,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,8,1953-02-25,1953-03-04,48.856614,2.352222,8
29,1950-01-04,Paris,France,NaN,NaN,y,SIU Box 14 folder 6; SIU Box 39 folder 2,48.8566,2.35222,True,6,1952-08-05,1952-08-10,48.856614,2.352222,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18077,1953-08-12,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.2827,-123.121,True,14,1953-08-03,1953-08-16,49.282729,-123.120738,1
18078,1953-08-13,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.2827,-123.121,True,14,1953-08-03,1953-08-16,49.282729,-123.120738,1
18079,1953-08-14,Vancouver,Canada,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; SIU ...,49.2827,-123.121,True,14,1953-08-03,1953-08-16,49.282729,-123.120738,1
18080,1953-08-15,Vancouver,Canada,NaN,NaN,y,SIU Box 16 folder 6; SIU Box 17 folder 7,49.2827,-123.121,True,14,1953-08-03,1953-08-16,49.282729,-123.120738,1
18081,1953-08-16,Vancouver,Canada,NaN,NaN,NaN,NaN,49.2827,-123.121,True,14,1953-08-03,1953-08-16,49.282729,-123.120738,1
18082,1953-08-18,"Crystal Bay, NV",USA,NaN,NaN,n,NaN,39.2278,-120.005,False,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18083,1953-08-19,"Crystal Bay, NV",USA,NaN,NaN,y,NaN,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18084,1953-08-20,"Crystal Bay, NV",USA,NaN,NaN,y,NaN,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18085,1953-08-21,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18086,1953-08-22,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18087,1953-08-23,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18088,1953-08-24,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 39 folder 5; SIU Box 16 folder 6; MHS Log,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18089,1953-08-25,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18090,1953-08-26,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18091,1953-08-27,"Crystal Bay, NV",USA,NaN,NaN,y,SIU Box 16 folder 6,39.2278,-120.005,True,9,1953-08-19,1953-08-27,39.227827,-120.004710,1
18092,1953-10-08,Havana,Cuba,NaN,NaN,n,NaN,23.1136,-82.3666,False,2,1953-10-09,1953-10-10,23.113592,-82.366596,1
18093,1953-10-09,Havana,Cuba,NaN,NaN,n,"FBI file; letter to Dale dated Oct 10, 1953 in...",23.1136,-82.3666,True,2,1953-10-09,1953-10-10,23.113592,-82.366596,1
18094,1953-10-10,Havana,Cuba,NaN,NaN,n,"letter to Dale dated Oct 10, 1953 in SIU Box 1...",23.1136,-82.3666,True,2,1953-10-09,1953-10-10,23.113592,-82.366596,1
18095,1953-10-13,Los Angeles,USA,NaN,NaN,y,"MHS Box 22, Personal Log",34.0522,-118.244,False,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18096,1953-10-14,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18097,1953-10-15,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18098,1953-10-16,Los Angeles,USA,NaN,NaN,y,SIU Box 16 folder 8,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18099,1953-10-17,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18100,1953-10-18,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18101,1953-10-19,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18102,1953-10-20,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18103,1953-10-21,Los Angeles,USA,NaN,NaN,y,SIU Box 16 folder 8,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18104,1953-10-22,Los Angeles,USA,NaN,NaN,y,NaN,34.0522,-118.244,True,9,1953-10-14,1953-10-22,34.052234,-118.243685,1
18105,1953-11-04,San Francisco,USA,NaN,NaN,NaN,NaN,37.7749,-122.419,False,1,1953-11-05,1953-11-04,37.774929,-122.419415,1
18106,1953-11-10,Beverly Hills,USA,NaN,NaN,n,SIU Box 16 folder 9,34.0736,-118.4,False,1,1953-11-11,1953-11-10,34.073620,-118.400356,1